<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'para_invalid_key' => "Sorry, that is not a valid IP Chat account number",
'para_help_title' => "Invision Power Chat (ParaChat)",
'addon_invalid_key' => "Sorry, that is not a valid IP Chat account number",
'addon_help_title' => "Invision Power Chat (AddonChat)",
 ); 
