<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'ipb_login' => "Invision Power Board: Log in",
'no_acp_access' => "You do not have permission to access the ACP",
'bad_email_password' => "Your login credentials were not valid",
'logout_complete' => "Log out complete",
'login_successful' => "Log in successful",
 ); 
