<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'email_member' => "<#MEMBER_NAME#>,

<#FROM_NAME#> has sent you this email from <#BOARD_ADDRESS#>.


<#MESSAGE#>

---------------------------------------------------
Please note that <#BOARD_NAME#> has no control over the
contents of this message.
---------------------------------------------------

",
'subject__subs_no_post' => "[<#TITLE#>] New Reply Notification",
'subs_no_post' => "<#NAME#>,

<#POSTER#> has just posted a reply to a topic that you have subscribed to titled \"<#TITLE#>\".

The topic can be found here:
<#BOARD_ADDRESS#>?showtopic=<#TOPIC_ID#>&view=getnewpost

There may be more replies to this topic, but only 1 email is sent per board visit for each subscribed topic. This is
to limit the amount of mail that is sent to your inbox.

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Topics\" link in the \"Forums\" tab.
",
'subject__complete_reg' => "Account: %s, validated at %s",
'complete_reg' => "
Success!

An administrator has accepted your registration request or email address change at <#BOARD_NAME#>. You may now log in with
your chosen details and access your full user account at <#BOARD_ADDRESS#>
",
'subject__subs_new_topic' => "[<#TITLE#>] New Topic Notification",
'subs_new_topic' => "<#NAME#>,

<#POSTER#> has just posted a new topic entitled \"<#TITLE#>\" in forum \"<#FORUM#>\".

----------------------------------------------------------------------
<#POST#>
----------------------------------------------------------------------

The topic can be found here:
<#BOARD_ADDRESS#>?showtopic=<#TOPIC_ID#>

Please note that if you wish to get email notification of any replies to this topic, you will have to click on the
\"Track this Topic\" link shown on the topic page, or by visiting the link below:
<#BOARD_ADDRESS#>?app=core&module=usercp&tab=forums&area=watch&watch=topic&do=list&tid=<#TOPIC_ID#>


Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Forums\" link in the \"Forums\" tab.
If you are not subscribed to any forums and wish to stop receiving notification, uncheck the setting
\"Send me any updates sent by the board administrator\" found in 'My Settings' under 'General Settings' in the \"Settings\" tab.
",
'subs_with_post' => "<#NAME#>,

<#POSTER#> has just posted a reply to a topic that you have subscribed to titled \"<#TITLE#>\".

----------------------------------------------------------------------
<#POST#>
----------------------------------------------------------------------

The topic can be found here:
<#BOARD_ADDRESS#>?showtopic=<#TOPIC_ID#>&view=getnewpost



If you have configured in your control panel to receive immediate topic reply notifications, you may receive an
email for each reply made to this topic.  Otherwise, only 1 email is sent per board visit for each subscribed topic. 
This is to limit the amount of mail that is sent to your inbox.

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Topics\" link in the \"Forums\" tab.
",
'newemail' => "
<#NAME#>,
This email has been sent from <#BOARD_ADDRESS#>.

You have received this email because you requested an
email address change.

------------------------------------------------
Activation Instructions Below
------------------------------------------------

We require that you \"validate\" your email address change to ensure that
you instigated this action. This protects against
unwanted spam and malicious abuse.

To activate your account, simply click on the following link:

<#THE_LINK#>

(Some email client users may need to copy and paste the link into your web
browser).

------------------------------------------------
Not working?
------------------------------------------------

If you could not validate your registration by clicking on the link, please
visit this page:

<#MAN_LINK#>

It will ask you for a user id number, and your validation key. These are shown
below:

User ID: <#ID#>

Validation Key: <#CODE#>

Please copy and paste, or type those numbers into the corresponding fields in the form.

Once the activation is complete, you may need to log back in to update your member group
permissions.

------------------------------------------------
Help! I get an error!
------------------------------------------------

If you cannot re-activate your account, it's possible that the account has been removed or you
are in the process of another activation, such as registering or changing your registered email address.
If this is the case, then please complete the previous activation.
If the error persists, please contact an administrator to rectify the problem.

",
'subject__subs_with_post' => "[<#TITLE#>] New Reply Notification",
'forward_page' => "
<#TO_NAME#>


<#THE_MESSAGE#>

---------------------------------------------------
Please note that <#BOARD_NAME#> has no control over the
contents of this message.
---------------------------------------------------
",
'lost_pass_email_pass' => "
<#NAME#>,
This email has been sent from <#BOARD_ADDRESS#>.

This email completes your lost password request.

------------------------------------------------
YOUR NEW PASSWORD
------------------------------------------------

Your username is: <#USERNAME#>
Your email address is: <#EMAIL#>
Your new password is: <#PASSWORD#>

Log in here: <#LOGIN#>

Please be careful to use the correct information (username or email address) to login to the site.

------------------------------------------------
CHANGING YOUR PASSWORD
------------------------------------------------

Once you've logged in, you can visit your User CP to
change your password.

User CP: <#THE_LINK#>

",
'admin_newuser' => "
Hello,

You have received this email because a new user has registered!

<#MEMBER_NAME#> completed their registration on <#DATE#>

You can turn off user notification in the Admin Control Panel

Have a super day!
",
'possibleSpammer' => "
Hello,

You have received this email because you chose to be notified when a possible spammer is flagged.

Name: <#MEMBER_NAME#>
Email: <#EMAIL#>
IP: <#IP#>
Registered: <#DATE#>

You can view this user here: <#LINK#>

Have a super day!
",
'lost_pass' => "
<#NAME#>,
This email has been sent from <#BOARD_ADDRESS#>.

You have received this email because a user account password recovery
was instigated by you on <#BOARD_NAME#>.

------------------------------------------------
IMPORTANT!
------------------------------------------------

If you did not request this password change, please IGNORE and DELETE this
email immediately. Only continue if you wish your password to be reset!

------------------------------------------------
Activation Instructions Below
------------------------------------------------

We require that you \"validate\" your password recovery to ensure that
you instigated this action. This protects against
unwanted spam and malicious abuse.

Simply click on the link below and complete the rest of the form

<#THE_LINK#>

(Some email client users may need to copy and paste the link into your web
browser).

------------------------------------------------
Not working?
------------------------------------------------

If you could not validate your registration by clicking on the link, please
visit this page:

<#MAN_LINK#>

It will ask you for a user id number, and your validation key. These are shown
below:

User ID: <#ID#>

Validation Key: <#CODE#>

Please copy and paste, or type those numbers into the corresponding fields in the form.

------------------------------------------------
Is this not working?
------------------------------------------------

If you cannot re-activate your account, it's possible that the account has been removed or you
are in the process of another activation, such as registering or changing your registered email address.
If this is the case, then please complete the previous activation.
If the error persists, please contact an administrator to rectify the problem.

IP address of sender: <#IP_ADDRESS#>

",
'reg_validate' => "
<#NAME#>,
This email has been sent from <#BOARD_ADDRESS#>.

You have received this email because this email address
was used during registration for our forums.
If you did not register at our forums, please disregard this
email. You do not need to unsubscribe or take any further action.

------------------------------------------------
Activation Instructions
------------------------------------------------

Thank you for registering.
We require that you \"validate\" your registration to ensure that
the email address you entered was correct. This protects against
unwanted spam and malicious abuse.

To activate your account, simply click on the following link:

<#THE_LINK#>

(Some email client users may need to copy and paste the link into your web
browser).

------------------------------------------------
Not working?
------------------------------------------------

If you could not validate your registration by clicking on the link, please
visit this page:

<#MAN_LINK#>

It will ask you for a user id number, and your validation key. These are shown
below:

User ID: <#ID#>

Validation Key: <#CODE#>

Please copy and paste, or type those numbers into the corresponding fields in the form.

If you still cannot validate your account, it's possible that the account has been removed.
If this is the case, please contact an administrator to rectify the problem.

Thank you for registering and enjoy your stay!
",
'subject__digest_topic_daily' => "Your daily new posts digest",
'digest_topic_daily' => "<#NAME#>,

This is the digest of posts in topic \"<#TITLE#>\" for today.

----------------------------------------------------------------------



<#CONTENT#>




----------------------------------------------------------------------

The topic can be found here:
<#BOARD_ADDRESS#>?showtopic=<#TOPIC_ID#>&view=getnewpost

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Topics\" link in the \"Forums\" tab.
",
'subject__new_comment_added' => "New Comment",
'new_comment_added' => "<#MEMBERS_DISPLAY_NAME#>,

<#COMMENT_NAME#> has left you a comment on your profile.

Manage your comments: <#LINK#>
",
'subject__new_topic_queue_notify' => "New Topic Awaiting Approval",
'new_topic_queue_notify' => "Hello!

This email has been sent from: <#BOARD_NAME#>.

A new topic has been entered into the moderation queue and is awaiting
approval.

----------------------------------
Topic: <#TOPIC#>
Forum: <#FORUM#>
Author: <#POSTER#>
Time: <#DATE#>
Manage Queue: <#LINK#>
----------------------------------

If you no longer require notification, you can stop these emails by simply
removing your email address from the forum settings options.

<#BOARD_ADDRESS#>

",
'subject__new_post_queue_notify' => "New Post Awaiting Approval",
'new_post_queue_notify' => "Hello!

This email has been sent from: <#BOARD_NAME#>.

A new post has been entered into the moderation queue and is awaiting
approval.

----------------------------------
Topic: <#TOPIC#>
Forum: <#FORUM#>
Author: <#POSTER#>
Time: <#DATE#>
Manage Queue: <#LINK#>
----------------------------------

If you no longer require notification, you can stop these emails by simply
removing your email address from the forum settings options.

<#BOARD_ADDRESS#>

",
'subject__digest_forum_weekly' => "Your weekly new topics digest",
'digest_forum_weekly' => "<#NAME#>,

This is the digest of this weeks posts in forum <#FORUM_NAME#>.

----------------------------------------------------------------------



<#CONTENT#>




----------------------------------------------------------------------

The forum can be found here:
<#BOARD_ADDRESS#>?showforum=<#FORUM_ID#>

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Topics\" link in the \"Forums\" tab.
",
'subject__digest_forum_daily' => "Your daily new topics digest",
'digest_forum_daily' => "<#NAME#>,

This your daily new topics digest!

----------------------------------------------------------------------



<#CONTENT#>




----------------------------------------------------------------------

The forum can be found here:
<#BOARD_ADDRESS#>?showforum=<#FORUM_ID#>

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Forums\" link in the \"Forums\" tab.
",
'subject__digest_topic_weekly' => "Your weekly new posts digest",
'digest_topic_weekly' => "<#NAME#>,

This your weekly new topics digest!

----------------------------------------------------------------------



<#CONTENT#>




----------------------------------------------------------------------

The forum can be found here:
<#BOARD_ADDRESS#>?showforum=<#FORUM_ID#>

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Manage Watched Forums\" link in the \"Forums\" tab.
",
'send_text' => "I thought you might be interested in reading this web page: <#THE LINK#>

From,

<#USER NAME#>
",
'subject__new_friend_added' => "Friend Added",
'new_friend_added' => "<#MEMBERS_DISPLAY_NAME#>,

<#FRIEND_NAME#> has successfully added you to their friends list.

Manage your friends: <#LINK#>
",
'subject__new_comment_request' => "New Comment Pending Approval",
'new_comment_request' => "<#MEMBERS_DISPLAY_NAME#>,

<#COMMENT_NAME#> has left you a comment that requires your approval.

As you've chosen to approve all new comments the new comment will not appear on your
profile until it's been approved.

Log in and then manage your comments: <#LINK#>
",
'subject__new_friend_approved' => "New Friend Approved",
'new_friend_approved' => "<#MEMBERS_DISPLAY_NAME#>,

<#FRIEND_NAME#> has approved your friend request!

Log in and then manage your friends: <#LINK#>
",
'subject__new_friend_request' => "New Friend Request",
'new_friend_request' => "<#MEMBERS_DISPLAY_NAME#>,

<#FRIEND_NAME#> wants to be your friend!

This message has been sent because <#FRIEND_NAME#> has added you to their friends
list. As you've chosen to approve all friend requests, you will need to visit your
friends list and approve them.

Log in and then manage your friends: <#LINK#>
",
'account_created' => "<#NAME#>,

Your account has been created successfully at <#BOARD_NAME#>.

If we were waiting on a parental consent form, this means the form has been received and documented.

Your details are as follows:

Username: <#NAME#>
Email Address: <#EMAIL#>
Password: <#PASSWORD#>

Please be aware that we do not store a plain text copy of your password, and you can change your password at any time through your control panel on the site.

Visit this link to join into our discussions!

<#BOARD_ADDRESS#>
",
'personal_convo_invite' => "<#NAME#>,

<#POSTER#> has added you to their personal conversation entitled \"<#TITLE#>\".

You can read this personal conversation by following the link below:

<#BOARD_ADDRESS#><#LINK#>
",
'subject__error_log_notification' => "An error has been generated on your site",
'error_log_notification' => "Dear admin,

An error has been generated on your forums.  You are being sent this notification based on your error log notification settings in the Admin Control Panel.  This error meets the criteria for errors that you have set to be notified about.

The error code is: <#CODE#>
The error message is: <#MESSAGE#>
The user who saw this error is: <#VIEWER#>
The IP address of this user is: <#IP_ADDRESS#>

Please login to your Admin Control Panel to use the error log viewer tool for further information.

<#BOARD_ADDRESS#>
",
'subject__account_created' => "Your account has been created",
'subject__personal_convo_invite' => "You have been added to a personal conversation",
'personal_convo_new_reply' => "<#NAME#>,

<#POSTER#> has replied to a personal conversation entitled \"<#TITLE#>\".

<#POSTER#> said:
======================================================================
<#TEXT#>
======================================================================

PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL!
You can reply to this personal conversation by following the link below:

<#BOARD_ADDRESS#><#LINK#>
",
'header' => "",
'footer' => "
Regards,

The <#BOARD_NAME#> team.
<#BOARD_ADDRESS#>
",
'subject__personal_convo_new_convo' => "You have been sent a new personal conversation",
'personal_convo_new_convo' => "<#NAME#>,

<#POSTER#> has sent you a new personal conversation entitled \"<#TITLE#>\".

<#POSTER#> said:
======================================================================
<#TEXT#>
======================================================================

PLEASE DO NOT REPLY DIRECTLY TO THIS EMAIL!
You can reply to this personal conversation by following the link below:

<#BOARD_ADDRESS#><#LINK#>
",
'subject__personal_convo_new_reply' => "A reply has been made to a personal conversation",
 ); 
