<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'ls_help' => "Help Files",
'ls_acppages' => "ACP Pages",
'ls_settings' => "Settings",
'ls_view_more_acp' => "View more ACP Pages",
'ls_quick_search' => "Quick Search",
'ls_view_more_settings' => "View more settings",
'ls_view_more_help' => "View more help files",
 ); 
