<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'back_topic' => "Back to the topic",
'o_html_title' => "Download HTML Version",
'o_html_desc' => "This will enable you to download a HTML version of this topic to your hard drive. This will open your browser's download dialogue box",
'o_word_title' => "Download Microsoft Word Version",
'o_word_desc' => "This will enable you to download a version of this topic in an editable Word format. This will open your browser's download dialogue box",
'o_print_desc' => "This will display the topic in a simple, printer friendly format on this page, no download is required.",
'o_print_title' => "Printer Friendly Version",
'start' => "started by",
'topic' => "Topic",
'tvo_title' => "Topic View Options for:",
'by' => "Posted by",
'title' => "Printable Version of Topic",
'on	' => "on",
'forum' => "Forum",
'end' => "end",
'please_choose' => "Please choose an option below",
'view_original' => "(View original topic)",
'click_toview' => "Click to view Topic",
'powered_by' => "Powered by ",
'posted_prefix' => "Posted",
 ); 
