<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'topic_noattach' => "The specified topic does not have any attachments",
'topic_noperms' => "You do not have permission to access this forum",
'leader_all_forums' => "All Forums",
'stats_missing_tid' => "You must select a valid topic for this feature",
'notopic_attach' => "Could not load attachments for the requested topic",
'leader_location' => "Location",
'leader_forums' => "Forums",
'leader_name' => "Member Name",
'leader_mods' => "Forum Moderators",
'leader_global' => "Global Moderators",
'leader_admins' => "Administrators",
'forum_leaders' => "The moderating team",
'top_poster_title' => "Today's top 20 posters",
'no_info' => "No information is available at this time",
'member_percent' => "% of today's posts",
'member_joined' => "Joined",
'member_posts' => "Total Member Posts",
'member_today' => "Posts Today",
'todays_posters' => "Today's Top 20 Posters",
'member' => "Member",
'goto_profile' => "Go to profile",
'whoposted_posts' => "Posts",
'whoposted_name' => "Member name",
'go_button' => "Go",
'who_replied_title' => "Who posted in this topic",
'no_forums' => "View Forums (%s total...)",
'who_farted' => "Who posted in:",
 ); 
