<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'sort_by' => "Sort by: ",
'mlist_view_start_title' => "View members starting with",
'mlist_view_all_title' => "View all members",
'mlist_adv_filt_opt' => "Advanced Filter Options",
'mlist_adv_filt' => "Use advanced filters",
'page_title' => "Member List",
'mlist_header' => "Member List",
'sort_by_joined' => "Join Date",
'sort_submit' => "Apply Filters",
'ascending_order' => "Ascending Order",
'descending_order' => "Descending Order",
'member_posts' => "Posts",
'member_name' => "Name",
'sorting_text_results' => "results per page",
'sorting_text_in' => "in",
'sorting_text_with' => "with",
'sorting_text_by' => "by",
'member_joined' => "Joined",
'sort_by_name' => "Member Name",
'no_results' => "No Results",
'member_group' => "Group",
's_after' => "after",
's_before' => "before",
's_contains' => "contains",
's_begins' => "begins with",
's_lessthan' => "less than",
's_dateformat' => "(MM-DD-YYYY)",
's_morethan' => "more than",
's_signature' => "Signature contains",
's_name' => "Member name",
'photo_only' => "Must have a photo",
's_lastpost' => "Last post is",
's_lastvisit' => "Last visit is",
's_posts' => "Post count is",
's_joined' => "Join date is",
'm_views' => "Views",
'm_stars' => "stars",
'm_rating_morethan' => "Rating is higher than",
'mlist_view_all_txt' => "ALL",
'm_rating' => "Rating",
'members_start_with' => "View members starting with ",
'm_dd_views' => "Profile Views",
'reputation' => "Reputation",
'sorty_by_jdate' => "Sort by Joined Date",
'pcount' => "Post Count",
'sort_by_posts' => "Total Posts",
'sort_by_mname' => "Sort by Member Name",
'show_all' => "Show All",
 ); 
