<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 06 Sep 2009 01:36:11 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'b_nobulk' => "No bulk mailings to display",
'b_create' => "Create new bulk mail",
'b_deletedot' => "Delete...",
'b_resenddot' => "Resend...",
'b_editdot' => "Edit...",
'b_cancel' => "Cancel",
'b_cancelconfirm' => "Click OK to cancel this mail",
'b_ltime' => "Time Taken",
'b_notyet' => "Not yet sent",
'b_minutes' => " minutes",
'b_inprogress' => "Sending mail in progress",
'b_lsenton' => "Sent On",
'b_lsentto' => "Sent To",
'b_qposts' => "<em>The number of posts for the mail recipient</em>",
'b_stored' => "Your stored bulk mail",
'b_lsubject' => "Subject",
'b_qmname' => "<em>The member name of the mail recipient</em>",
'b_qjoin' => "<em>The join date of the mail recipient</em>",
'b_qid' => "<em>The member ID of the mail recipient</em>",
'b_qonlinetime' => "<em>The time that the most number of members were online</em>",
'b_qbname' => "<em>The name of your board</em>",
'b_qboardurl' => "<em>The URL to your board</em>",
'b_qmtotal' => "<em>The total number of registered members</em>",
'b_qonline' => "<em>The most number of users online</em>",
'b_qptotal' => "<em>The total number of posts</em>",
'b_qtag_info' => "You may use the following 'quick tags' in your mail and they will be converted when the mail is sent.",
'b_njoined' => "Send to members who joined <em><strong>n</strong></em> days ago",
'b_leaveblank' => "Leave blank to not filter",
'b_preview' => "Preview",
'b_qtag' => "Quick Tags",
'b_ndays' => "Send to members whose last visit was <em><strong>n</strong></em> days ago",
'b_addfilters' => "<strong>Additional Filters</strong>",
'b_nposts' => "Send to members with <em><strong>n</strong></em> posts",
'b_step2' => "Step 2: Filters",
'b_groups' => "<strong>Send to Groups:</strong>",
'b_html' => "Send mail in HTML format? (Full HTML formatting &amp; and tags allowed)",
'b_honor' => "Honor the '<strong>Send me any updates seny by the board administrator</strong>' setting? This will only mail members who have opted in.",
'b_content' => "<strong>Mail Content</strong>",
'b_options' => "Options",
'b_subject' => "<strong>Mail Subject</strong>",
'b_edit' => "Edit Mail",
'b_editstored' => "Editing Stored Mail",
'b_step1' => "Step 1: Start New Bulk Mail",
'b_proceed' => "Proceed...",
'b_step1_title' => "Mail Details",
'b_lessthan' => "less than",
'b_morethan' => "more than",
'b_percycle' => "<strong>Number sent per cycle</strong>",
'b_mailbutton' => "Start Sending The Mail",
'b_sending_info' => "Clicking the 'Start Sending The Mail' button below will activate the task manager's send bulk mail function which will send the mail in batches until the all the mail has been sent. You can watch the progress from the main Bulk Mail screen and cancel the mail from being sent.<br />We strongly recommend that you opt to send 20 mails per cycle as a maximum. Any more per cycle could severly affect performance of your server while the mail is being sent out.<br /><br />As the mail is sent out in cycles of <em><b>n</b></em> &nbsp;per minute, it can take a while to process all the mail.",
'b_sending' => "<strong>Sending the Mail</strong>",
'b_maildetails' => "<strong>Mail Details</strong>",
'b_editmail' => "Edit This Mail",
'b_countmember' => "Sending the bulk mail to <strong>%s</strong> members",
'b_maillogedit' => "Bulk mail ( %s ) edited",
'b_edited' => "Bulk mail edited!",
'b_mailcontents' => "{member_name},



-------------------------------------
{board_name} Statistics:
-------------------------------------
Registered Users: {reg_total}
Total Posts: {total_posts}
Busiest Time: {busy_count} users were online on {busy_time}

-------------------------------------
Handy Links
-------------------------------------
Board Address: {board_url}
Log In: {board_url}?app=core&module=global&section=login
Lost Password Recovery: {board_url}?app=core&module=global&section=lostpass

-------------------------------------
How to unsubscribe
-------------------------------------
Visit your email preferences ({board_url}?app=core&module=usercp) and ensure that the box for 'Send me any updates sent by the board administrator' is unchecked and submit the form",
'b_maillogadd' => "Bulk mail ( %s ) added",
'b_nonefound' => "Your criteria didn't match any members. Please adjust your current criteria, ensuring all correct fields are selected or entered.",
'b_nogroups' => "You must select at least one group to send this mail message to. Please try again.",
'b_entercont' => "You must enter a mail subject and mail content before submitting. Please try again.",
'b_initiated' => "Bulk mail initiated!",
'b_noid' => "There was no ID passed to the mailer. Please try again.",
'b_norecord' => "Could not find the bulk mail record you requested. Please try again.",
'b_nosend' => "Cannot send - the mail doesn't have a subject and content. Please try again.",
'b_cancelled' => "Bulk mail cancelled!",
'b_deleted' => "Bulk mail deleted!",
'b_title' => "Bulk Mail Management",
 ); 
