<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:03 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_1 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- birthday --*/
function birthday($user, $pyear) {
$IPBHTML = "";
$IPBHTML .= "<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$user['member_id']}", 'public','' ), "{$user['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$user['members_display_name']}</a> " . (($pyear) ? ("(<strong>{$pyear}</strong>)") : ("")) . "";
return $IPBHTML;
}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";

$this->templateVars['sidebar_enabled'] = "$show_side_blocks";
$this->__default__templateVars['sidebar_enabled'] = "$show_side_blocks";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "
" . $this->registry->getClass('output')->addJSModule("hooks", "0" ) . "<script type='text/javascript'>
//<![CDATA[
	ipb.global.boardMarkers = $H({
		'f_cat_unread': \"" . $this->registry->getClass('output')->getReplacement("f_cat_read") . "\",
		'f_unread': \"" . $this->registry->getClass('output')->getReplacement("f_read") . "\",
		'f_pass_unread': \"" . $this->registry->getClass('output')->getReplacement("f_pass_read") . "\"
	});
	var markerURL = \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&module=ajax&section=markasread&secure_key={$this->member->form_hash}&i=1&forumid=", 'public','' ), "", "" ) . "\"; // Ajax URL so don't use &amp;
//]]>
</script>
" . (($this->templateVars['sidebar_enabled']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=toggle", 'public','' ), "", "" ) . "' id='close_sidebar'  class='sidebar_toggle rounded' " . ((IPSCookie::get('hide_sidebar') != '1') ? ("style='display: none'") : ("")) . "><img src='{$this->settings['img_url']}/sidebar_close.png' alt='{$this->lang->words['sidebar_close']}' /></a>
	<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=toggle", 'public','' ), "", "" ) . "' id='open_sidebar' class='sidebar_toggle rounded' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . "><img src='{$this->settings['img_url']}/sidebar_open.png' alt='{$this->lang->words['sidebar_open']}' /></a>") : ("")) . "
<h2 class='hide'>{$this->lang->words['board_index_title']}</h2>
<div id='board_index' class='clearfix'>
	" . (($this->templateVars['sidebar_enabled']) ? ("<div id='index_stats' class='right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">
			".$this->__f__ff88473eff708eb9314ce7282dac4715($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks)."		</div>") : ("")) . "
	
	
	<div id='categories' class='" . ((IPSCookie::get('hide_sidebar') == '1' || !$this->templateVars['sidebar_enabled']) ? ("no_sidebar") : ("")) . " clearfix'>
		" . ((is_array($news_data) AND count($news_data)) ? ("
			<div id='latest_news' class='row2'><strong>{$this->lang->words['newslink']}</strong> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$news_data['id']}", 'public','' ), "{$news_data['seo_title']}", "showtopic" ) . "' title='{$this->lang->words['newslink']}'>{$news_data['title']}</a></div>
		") : ("")) . "
	<!-- CATS AND FORUMS -->
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__055700bb587a2b33772bc541b89a163e($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
</div>
<ul id='stat_links' class='filter_bar rounded'>
	<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=active", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['today_active_cont']}\">{$this->lang->words['new_active_cont']}</a></li>
	<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=leaders", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['sm_forum_leaders_title']}\">{$this->lang->words['sm_forum_leaders']}</a></li>
	<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['sm_all_posters_title']}\">{$this->lang->words['sm_today_posters']}</a></li>
	<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=view&amp;module=list&amp;max_results=20&amp;sort_key=posts&amp;sort_order=desc&amp;filter=ALL", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['sm_overall_posters_title']}\">{$this->lang->words['sm_overall_posters']}</a></li>
</ul>
<div id='board_statistics' class='statistics general_box clearfix'>
	" . (($this->settings['show_totals']) ? ("
		<div id='stats'>
			<h2>{$this->lang->words['board_stats']}</h2>
			<dl>
				<dt>{$this->lang->words['total_posts']}</dt>
				<dd>{$stats['info']['total_posts']}</dd>
				<dt>{$this->lang->words['total_members']}</dt>
				<dd>{$stats['info']['mem_count']}</dd>
				<dt>{$this->lang->words['newest_member']}</dt>
				<dd><a href='{$stats['info']['last_mem_link']}' title='{$this->lang->words['view_profile']}'>{$stats['info']['last_mem_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($stats['info']['last_mem_id'],$stats['info']['last_mem_seo']) . "&nbsp;</dd>
				<dt>{$this->lang->words['online_at_once']}</dt>
				<dd>{$stats['info']['most_online']}<br /><span class='extra'>{$this->lang->words['on']} {$stats['info']['most_time']}</span></dd>
			</dl>
		</div>
	") : ("")) . "
	" . (($this->settings['show_active']) ? ("<div id='active_users' class='stats_list'>
			<h2>
				{$stats['TOTAL']} {$this->lang->words['active_users_text']} <span>{$this->lang->words['active_users']}</span><br />
				<span class='desc'>{$stats['MEMBERS']} {$this->lang->words['members']}, {$stats['GUESTS']} {$this->lang->words['guests']}, {$stats['ANON']} {$this->lang->words['anon_users']} | {$this->lang->words['show_by']}: <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_order=desc", 'public','' ), "", "" ) . "'>{$this->lang->words['oul_click']}</a> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_key=name&amp;sort_order=asc&amp;show_mem=reg", 'public','' ), "", "" ) . "'>{$this->lang->words['oul_name']}</a></span>
			</h2>
			" . ((count($stats['NAMES'])) ? ("
				<p>
					<span class='name'>" . implode( ",</span> <span class='name'>", $stats['NAMES'] ) . "</span>					
				</p>
			") : ("")) . "
		</div>") : ("")) . "
	" . (($calendar_events) ? ("<div id='cal_events' class='stats_list'>
		<h2>{$this->lang->words['upcoming_events']}</h2>
		" . ((is_array( $calendar_events )) ? ("
			<p>
				<span class='name'>" . implode( ",</span> <span class='name'>", $calendar_events ) . "</span>
			</p>
		") : ("
			<p>{$calendar_events}</p>
		")) . "
	</div>") : ("")) . "
	
	" . (($birthdays !== FALSE AND is_array( $birthdays['users'] ) AND count( $birthdays['users'] )) ? ("
		<div id='cal_bdays' class='stats_list'>
			<h2>{$birthdays['count']} {$this->lang->words['birthdays_today']}</h2>
			<p>
				<span class='name'>" . implode( ",</span> <span class='name'>", $birthdays['users'] ) . "</span>					
			</p>
		</div>
	") : ("" . (($this->settings['show_birthdays'] AND !$this->settings['autohide_bday']) ? ("
			<div id='cal_bdays' class='stats_list'>
				<h2>0 {$this->lang->words['birthdays_today']}</h2>
				<p>{$this->lang->words['no_birth_users']}</p>
			</div>
		") : ("")) . "")) . "
	
</div>
" . (($this->memberData['members_auto_dst'] == 1 AND $this->settings['time_dst_auto_correction']) ? ("
<script type='text/javascript'>
	ipb.vars['dst_on']	= parseInt(\"{$this->memberData['dst_in_use']}\");
	
	ipb.board.checkDST();
</script>
") : ("")) . "";
return $IPBHTML;
}


function __f__ff88473eff708eb9314ce7282dac4715($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.side_blocks.outer.pre-->';
	foreach( $side_blocks as $block )
	{
		
		$_ips___x_retval .= "
				{$block}
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__af69cc53a0116da3f8df4fc22cead137($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$_ips___x_retval .= "
													" . (($__data[3]) ? ("<li class='newposts'>") : ("<li>")) . "<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", 'public','' ), "{$__data[2]}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$__data[1]}</a></li>
												
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__0a7a856c707db47f35a8bb03445f6b86($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$_ips___x_retval .= "
								" . (($forum_data['redirect_on']) ? ("
									<tr class='" .  IPSLib::next( $this->registry->templateStriping["catTable"] ) . " redirect_forum'>
										<td class='altrow'>" . $this->registry->getClass('output')->getReplacement("f_redirect") . "</td>
										<td>
											<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", 'public','' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$forum_data['name']}</a></h4>
											<p class='desc'>{$forum_data['description']}</p>
										</td>
										<td colspan='2'>
											{$this->lang->words['rd_hits']}: " . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . "
										</td>
									</tr>
								") : ("<tr class='" .  IPSLib::next( $this->registry->templateStriping["catTable"] ) . "'>
										<td class='altrow'>
											<!-- SKINNOTE: this URL is wrong, needs updating -->
											" . (($forum_data['img_new_post'] != 'f_locked' && strstr( $forum_data['img_new_post'], 'unread' )) ? ("
												<a id='forum_img_{$forum_data['id']}' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['bi_markread']}\" class='forum_marker'>
													" . $this->registry->getClass('output')->getReplacement("{$forum_data['img_new_post']}") . "
												</a>
									
												<script type='text/javascript'>
													ipb.global.registerMarker( \"forum_img_{$forum_data['id']}\", \"{$forum_data['img_new_post']}\", markerURL + \"{$forum_data['id']}\" );
												</script>
											") : ("
												" . $this->registry->getClass('output')->getReplacement("{$forum_data['img_new_post']}") . "
											")) . "
										</td>
										<td>
											<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", 'public','' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$forum_data['name']}</a></h4>
											<p class='desc'>{$forum_data['description']}</p>
									
											" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums']) ? ("
												<h5 class='hide'>{$this->lang->words['subforums']}</h5>
												<ol class='subforums'>
												".$this->__f__af69cc53a0116da3f8df4fc22cead137($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."												</ol>
											") : ("")) . "
											<!-- Skinnote: Clean up queued stuff -->
											" . ((!empty($forum_data['_has_queued_and_can_see_icon'])) ? ("
												<em class='moderated'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;modfilter=all", 'public','' ), "{$forum_data['name_seo']}", "showforum" ) . "' title='{$this->lang->words['view_unapproved']}'>" . sprintf( $this->lang->words['f_queued'], $forum_data['queued_topics'], $forum_data['queued_posts']) . "</a></em>
											") : ("")) . "
										</td>
										<td class='altrow stats'>
											<ul>
												<li>{$forum_data['topics']} {$this->lang->words['topics']}</li>
												<li>{$forum_data['posts']} {$this->lang->words['replies']}</li>
											</ul>
										</td>
										<td>
											<ul class='last_post'>
												" . (($forum_data['hide_last_info']) ? ("
													<li>{$this->lang->words['f_protected']}</li>
												") : ("" . (($forum_data['_hide_last_date']) ? ("
														<li>{$forum_data['last_post']}</li>
													") : ("
														<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", 'public','' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . $this->registry->getClass('output')->getReplacement("f_lastpost") . "</a> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", 'public','' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>{$forum_data['last_post']}</a></li>
													")) . "
													<li><strong>{$this->lang->words['in']}</strong> {$forum_data['last_topic_title']}</li>
													<li>
														<strong>{$this->lang->words['by']}</strong> 
														" . ((isset($forum_data['last_poster_name']) AND $forum_data['last_poster_name']) ? ("" . (($forum_data['last_poster_id']) ? ("
																<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$forum_data['last_poster_id']}", 'public','' ), "{$forum_data['seo_last_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$forum_data['last_poster_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($forum_data['last_poster_id'], $forum_data['seo_last_name']) . "
															") : ("
																{$this->settings['guest_name_pre']}{$forum_data['last_poster_name']}{$this->settings['guest_name_suf']}
															")) . "") : ("
															{$this->lang->words['f_none']}
														")) . "
													</li>")) . "
											</ul>
										</td>
									</tr>")) . "
							
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__055700bb587a2b33772bc541b89a163e($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	foreach( $cat_data as $_data )
	{
		
$this->registry->templateStriping['catTable'] = array( FALSE, "row1","row2");

		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
										<div class='category_block block_wrap'>
						<h3 id='category_{$_data['cat_data']['id']}' class='maintitle'><a class='toggle right' href='#' title='{$this->lang->words['toggle_cat']}'>{$this->lang->words['toggle_cat']}</a> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", 'public','' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['view_cat']}'>{$_data['cat_data']['name']}</a></h3>
						<table class='ipb_table' summary=\"{$this->lang->words['forums_in_cat']} '{$_data['cat_data']['name']}'\">
							<tr class='header'>
								<th scope='col' class='col_c_icon'>&nbsp;</th>
								<th scope='col' class='col_c_forum'>{$this->lang->words['cat_name']}</th>
								<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>
								<th scope='col' class='col_c_post'>{$this->lang->words['last_post_info']}</th>
							</tr>
							<!-- / CAT HEADER -->
							".$this->__f__0a7a856c707db47f35a8bb03445f6b86($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks,$_data)."						</table>
					</div>
				") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($rows) {
$IPBHTML = "";

$this->registry->templateStriping['recent_status'] = array( FALSE, "row1","row2 altrow");
$IPBHTML .= "<script type='text/javascript'>
var _hC = 0;
function statusHookClick(o)
{
	if ( ! _hC )
	{
		o.value = '';
		o.setStyle( { color: 'black' } );
		_hC++;
	}
}
</script>
<div class='general_box clearfix'>
	<h3><img src='{$this->settings['img_url']}/user_comment.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['recent_status_updates']}</h3>
	" . (($this->memberData['member_id'] AND $this->memberData['g_mem_info'] AND ! $this->memberData['gbw_no_status_update']) ? ("
		<form id='update_status_form' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status' method='post'>
			<fieldset>
				<input type='hidden' name='k' value='{$this->member->form_hash}' />
				<input type='hidden' name='rurl' value='" . base64_encode('act=idx') . "' />
			</fieldset>
			<p style='padding-top:4px;padding-bottom:6px'><span class='left' style='margin-right: 5px;margin-top:-2px'><img src='{$this->memberData['pp_mini_photo']}' width='{$this->memberData['pp_mini_width']}' height='{$this->memberData['pp_mini_height']}' class='photo' alt=\"{$this->memberData['members_display_name']}{$this->lang->words['users_photo']}\" /></span><input type='text' class='input_text' size='30' maxlength='150' style='color:gray' value=\"{$this->lang->words['update_status_default']}\" onclick='statusHookClick(this)' name='new_status' /> <input type='submit' class='input_submit' value=' &raquo; ' /></p>
		</form>
	") : ("")) . "
	<ul class='hfeed block_list'>
		" . ((is_array( $rows ) && count( $rows )) ? ("
						".$this->__f__b78715bd6707528bae34bdf7361e0ac9($rows)."		") : ("
			<li>{$this->lang->words['norecent_status_updates']}</li>
		")) . "
	</ul>
	
</div>";
return $IPBHTML;
}


function __f__b78715bd6707528bae34bdf7361e0ac9($rows)
{
	$_ips___x_retval = '';
	foreach( $rows as $r )
	{
		
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_status"] ) . "'>
					<span class='left' style='margin-right: 5px;'><img src='{$r['pp_mini_photo']}' width='{$r['pp_mini_width']}' height='{$r['pp_mini_height']}' class='photo' alt=\"{$r['members_display_name']}{$this->lang->words['users_photo']}\" /></span><address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['pp_member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a></address>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['pp_member_id'], $r['members_seo_name']) . "<strong> {$r['pp_status']}</strong><br />
					<span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['pp_status_update'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['pp_status_update'],"short", 0) . "</abbr></span>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookRecentBlogEntries --*/
function hookRecentBlogEntries($entries) {
$IPBHTML = "";

$this->registry->templateStriping['recent_entries'] = array( FALSE, "row1","row2 altrow");
$IPBHTML .= "<div class='general_box clearfix'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['recently_added_entries']}</h3>
		<ul class='hfeed block_list'>
			" . ((is_array( $entries ) && count( $entries )) ? ("
								".$this->__f__72f27ffdf1fe6859901e597bc2cc0883($entries)."			") : ("
				<li>{$this->lang->words['norecent_entries_hook']}</li>
			")) . "
		</ul>
	</div>";
return $IPBHTML;
}


function __f__72f27ffdf1fe6859901e597bc2cc0883($entries)
{
	$_ips___x_retval = '';
	foreach( $entries as $r )
	{
		
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_entries"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$r['blog_id']}&amp;showentry={$r['entry_id']}", 'public','' ), "{$r['_seo_entry_name']}", "showentry" ) . "' rel='bookmark' title='{$this->lang->words['view_entry']}'>{$r['entry_name']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['entry_author_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['entry_author_id'], $r['members_seo_name']) . "</address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['entry_date'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['entry_date'],"short", 0) . "</abbr></span></li>
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookRecentGalleryImages --*/
function hookRecentGalleryImages($rows) {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$this->lang->words['recent_gallery_images']}</div>
<div id='attach_wrap' class='rounded clearfix'>
	<ul>
	".$this->__f__0e90ffe7f34ce34abae5eebcc5840ef5($rows)."	</ul>
</div>
<br style='clear:both;' />";
return $IPBHTML;
}


function __f__0e90ffe7f34ce34abae5eebcc5840ef5($rows)
{
	$_ips___x_retval = '';
	foreach( $rows as $r )
	{
		
		$_ips___x_retval .= "
		<li>{$r['_image']}</li>
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";

$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
$IPBHTML .= "<div class='general_box clearfix'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['recently_added_topics']}</h3>
		<ul class='hfeed block_list'>
			" . ((is_array( $topics ) && count( $topics )) ? ("
								".$this->__f__5ca7426619968f2bb22bf0ffee7e7612($topics)."			") : ("
				<li>{$this->lang->words['norecent_topics_hook']}</li>
			")) . "
		</ul>
	</div>";
return $IPBHTML;
}


function __f__5ca7426619968f2bb22bf0ffee7e7612($topics)
{
	$_ips___x_retval = '';
	foreach( $topics as $r )
	{
		
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", 'public','' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> 
				{$this->lang->words['recent_by']} <address class=\"author vcard\">" . (($r['members_display_name']) ? ("<a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['starter_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['starter_id'], $r['members_seo_name']) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "</address><br />
				<span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['start_date'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0) . "</abbr></span></li>
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookTopPosters --*/
function hookTopPosters($posters) {
$IPBHTML = "";
$IPBHTML .= "<div class='general_box clearfix'>
		<h3><img src='{$this->settings['img_url']}/user_comment.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['todays_top_posters']}</h3>
			" . ((is_array($posters) AND count($posters)) ? ("
				<ol id='top_posters' class='block_list clearfix'>
				".$this->__f__9e620f9e39fd9fb3274511d2849bb0d7($posters)."			</ol>
			") : ("")) . "
	</div>";
return $IPBHTML;
}


function __f__9e620f9e39fd9fb3274511d2849bb0d7($posters)
{
	$_ips___x_retval = '';
	foreach( $posters as $r )
	{
		
		$_ips___x_retval .= "
					<li>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><img src='{$r['pp_thumb_photo']}' width='{$r['pp_thumb_width']}' height='{$r['pp_thumb_height']}' alt='{$this->lang->words['photo']}' class='photo' /></a><br />
						<span class='name'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['members_display_name_short']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id'], $r['members_seo_name']) . " ({$r['tpost']})</span>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookWatchedItems --*/
function hookWatchedItems($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums) {
$IPBHTML = "";

$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");

$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
$IPBHTML .= "<div class='general_box alt clearfix' id='hook_watched_items'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['wi_content_title']}</h3>
		<div class='recent_activity'>
			<ol class='tab_bar no_title mini'>
				<li id='tab_link_forums' class='tab_toggle active clickable'>{$this->lang->words['watched_forums']}</li>
				<li id='tab_link_topics' class='tab_toggle clickable'>{$this->lang->words['watched_topics']}</li>
			</ol>
			<div id='tab_content_forums' class='tab_toggle_content'>
				" . ((is_array( $updatedForums ) && count( $updatedForums )) ? ("
					<ul class='clearfix'>
												".$this->__f__5f64f1a65e6060dcf6ee724bd87dcc83($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."					</ul>
				") : ("<ul class='clearfix'>
						" . ((!is_array( $nUpdatedForums ) OR !count( $nUpdatedForums )) ? ("
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'>{$this->lang->words['wi_not_watch']}</li>
						") : ("")) . "
					</ul>")) . "
				" . ((is_array( $nUpdatedForums ) && count( $nUpdatedForums )) ? ("
					<div id='more-watched-forums-container' style='display:none;'>
						<ul>
							".$this->__f__24bc20313e4953b296713287be3ddf05($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."						</ul>
					</div>
					<fieldset class='submit'>
						<input type='button' class='input_submit alt clickable' id='more-watched-forums' value='{$this->lang->words['wi_toggle_start']} {$this->lang->words['wi_toggle_end']}' />
					</fieldset>
				") : ("")) . "
			</div>
			
			<div id='tab_content_topics' class='tab_toggle_content' style='display:none;'>
								" . ((is_array( $updatedTopics ) && count( $updatedTopics )) ? ("
					<ul class='hfeed'>
						".$this->__f__58084f5d741db470446965873408a819($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."					</ul>
				") : ("" . ((!is_array( $nUpdatedTopics ) OR !count( $nUpdatedTopics )) ? ("
						<ul class='hfeed'>
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'>{$this->lang->words['wi_no_topics']}</li>
						</ul>
					") : ("")) . "")) . "
				" . ((is_array( $nUpdatedTopics ) && count( $nUpdatedTopics )) ? ("
					<div id='more-watched-topics-container' style='display:none;'>
						<ul class='hfeed'>
							".$this->__f__10b070c0fbf318be704ee05adde75219($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."						</ul>
					</div>
					<fieldset class='submit'>
						<input type='button' id='more-watched-topics' class='input_submit alt clickable' value='{$this->lang->words['wi_toggle_start']} {$this->lang->words['wi_t_toggle_end']}' />
					</fieldset>
				") : ("")) . "
			</div>
		</div>
	</div>";
return $IPBHTML;
}


function __f__5f64f1a65e6060dcf6ee724bd87dcc83($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	foreach( $updatedForums as $r )
	{
		
		$_ips___x_retval .= "
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$r['id']}", 'public','' ), "{$r['name_seo']}", "showforum" ) . "' rel='bookmark' title='{$this->lang->words['view_forum']}'>{$r['name']}</a></li>
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__24bc20313e4953b296713287be3ddf05($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	foreach( $nUpdatedForums as $r )
	{
		
		$_ips___x_retval .= "
								<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$r['id']}", 'public','' ), "{$r['name_seo']}", "showforum" ) . "' rel='bookmark' title='{$this->lang->words['view_forum']}'>{$r['name']}</a><br />
									<span class='desc'>{$this->lang->words['wi_no_new']}</span>
								</li>
							
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__58084f5d741db470446965873408a819($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	foreach( $updatedTopics as $r )
	{
		
		$_ips___x_retval .= "
							<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}&amp;view=getnewpost", 'public','' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['last_poster_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['last_poster_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['last_poster_id'], $r['members_seo_name']) . "</address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['last_post'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['last_post'],"short", 0) . "</abbr></span></li>
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__10b070c0fbf318be704ee05adde75219($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	foreach( $nUpdatedTopics as $r )
	{
		
		$_ips___x_retval .= "
								<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}&amp;view=getnewpost", 'public','' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['last_poster_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['last_poster_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['last_poster_id'], $r['members_seo_name']) . "</address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['last_post'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['last_post'],"short", 0) . "</abbr></span></li>
							
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- whoschatting_empty --*/
function whoschatting_empty() {
$IPBHTML = "";
$IPBHTML .= "<div id='active_chat' class='stats_list'>
			<h2>
				{$this->lang->words['whoschatting_total']} {$this->lang->words['whoschatting_loadchat']}
			</h2>
			{$this->lang->words['whoschatting_none']}
		</div>";
return $IPBHTML;
}

/* -- whoschatting_show --*/
function whoschatting_show($total="",$names="") {
$IPBHTML = "";
$IPBHTML .= "<div id='active_chat' class='stats_list'>
			<h2>
				{$total} {$this->lang->words['whoschatting_total']} {$this->lang->words['whoschatting_loadchat']}
			</h2>
			" . ((count($names)) ? ("
				<ul>
					<li>" . implode( ",</li><li>", $names ) . "</li>
				</ul>
			") : ("")) . "
		</div>";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>