<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:04 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_1 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- activePostsView --*/
function activePostsView($results, $pagination, $total, $asForum) {
$IPBHTML = "";

$this->registry->templateStriping['searchStripe'] = array( FALSE, "row1","row2");
$IPBHTML .= "<h2>" . sprintf($this->lang->words['active_content'], $this->lang->words['actperiod_' . $this->request['period'] ]) . "</h2>
<p class='message'>
	{$this->lang->words['active_have_been']} <em><strong>{$total}</strong></em> " . sprintf($this->lang->words['active_entries'], $this->lang->words['actperiod_' . $this->request['period'] ]) . "
</p>
<br />
<div class='topic_controls'>
{$pagination}
</div>
<ol id='member_alpha' class='tab_bar no_title'>
	".$this->__f__46f3f111624daaa8eb81342c9aa1ea50($results,$pagination,$total,$asForum)."</ol>
" . (($total) ? ("" . (($asForum) ? ("
		<table class='ipb_table topic_list' id='forum_table'>
			<tr class='header'>
				<th scope='col' class='col_f_icon'>&nbsp;</th>
				<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
				<th scope='col' class='col_f_starter'>{$this->lang->words['forum_forum']}</th>
				<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
				<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
				<th scope='col' class='col_f_post'>{$this->lang->words['forum_last_post_info']}</th>
			</tr>
			".$this->__f__f1338bc21407ef4882383917a90aab8f($results,$pagination,$total,$asForum)."		</table>
	") : ("
				<div id='search_results'>
			<ol>
				".$this->__f__289c29d9341e7269195acbd70f3ab1a5($results,$pagination,$total,$asForum)."			</ol>
		</div>
	")) . "") : ("
	<div class='no_messages'>{$this->lang->words['active_none']}</div>
")) . "
<div class='filter_bar rounded clear'>
	<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=active&amp;search_filter_app[{$app['app_directory']}]=1", 'public','' ), "", "" ) . "' method='post'>
	<div class='right clearfix'>
		{$this->lang->words['getactive_for']} 
		<select name='period'>
			<option value='today'" . (($this->request['period']=='today') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_today']}</option>
			<option value='week'" . (($this->request['period']=='week') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_week']}</option>
			<option value='weeks'" . (($this->request['period']=='weeks') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_weeks']}</option>
			<option value='month'" . (($this->request['period']=='month') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_month']}</option>
			<option value='months'" . (($this->request['period']=='months') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_months']}</option>
			<option value='year'" . (($this->request['period']=='year') ? (" selected='selected'") : ("")) . ">{$this->lang->words['actperiod_year']}</option>
		</select>&nbsp;
		<input type=\"submit\" name=\"gobutton\" value=\"{$this->lang->words['active_go']}\" class=\"input_submit alt\" />
	</div>
	</form>
</div>
" . (($total) ? ("
	<br class='clear' />{$pagination}
") : ("")) . "";
return $IPBHTML;
}


function __f__46f3f111624daaa8eb81342c9aa1ea50($results, $pagination, $total, $asForum)
{
	$_ips___x_retval = '';
	foreach( $this->registry->getApplications() as $app )
	{
		
		$_ips___x_retval .= "
		" . ((IPSSearchIndex::appIsSearchable( $app['app_directory'] )) ? ("" . (($this->request['search_app'] == $app['app_directory']) ? ("<li class='active'><strong>" . ((strtolower($app['app_title']) == 'system') ? ("{$this->lang->words['livesearch_helpfiles']}") : ("" . IPSLib::getAppTitle( $app['app_directory'] ) . "")) . "</strong></li>") : ("<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=active&amp;search_filter_app[{$app['app_directory']}]=1&amp;period={$this->request['period']}", 'public','' ), "", "" ) . "'>" . ((strtolower($app['app_title']) == 'system') ? ("{$this->lang->words['livesearch_helpfiles']}") : ("" . IPSLib::getAppTitle( $app['app_directory'] ) . "")) . "</a></li>")) . "") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__f1338bc21407ef4882383917a90aab8f($results, $pagination, $total, $asForum)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "
				{$result['html']}
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__289c29d9341e7269195acbd70f3ab1a5($results, $pagination, $total, $asForum)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "	
					" . (($result['sub']) ? ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " sub clearfix clear'>
							{$result['html']}
						</li>
					") : ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " clearfix clear'>
							{$result['html']}
						</li>
					")) . "
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- calEventRangedSearchResult --*/
function calEventRangedSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<div class='result_info'>
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;cal_id={$r['type_id']}&amp;do=showevent&amp;event_id={$r['type_id_2']}&amp;hl={$this->request['search_higlight']}", 'public','' ), "", "" ) . "'>{$r['content_title']}</a> (" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . " {$this->lang->words['to']} " . $this->registry->getClass('class_localization')->getDate($r['misc'],"short", 0) . ")</h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['content']}
	</p>
	") : ("")) . "
</div>
<div class='result_details desc'>
	<ul>
		<li>{$this->lang->words['search_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id']) . "</li>
	</ul>
</div>";
return $IPBHTML;
}

/* -- calEventSearchResult --*/
function calEventSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<div class='result_info'>
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;cal_id={$r['type_id']}&amp;do=showevent&amp;event_id={$r['type_id_2']}&amp;hl={$this->request['search_higlight']}", 'public','' ), "", "" ) . "'>{$r['content_title']}</a> (" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . " {$this->lang->words['to']} " . $this->registry->getClass('class_localization')->getDate($r['misc'],"short", 0) . ")</h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['content']}
	</p>
	") : ("")) . "
</div>
<div class='result_details desc'>
	<ul>
		<li>{$this->lang->words['search_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id']) . "</li>
	</ul>
</div>";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums) {
$IPBHTML = "";
$IPBHTML .= "<fieldset id='app_filter_forums' class='" .  IPSLib::next( $this->registry->templateStriping["search"] ) . " extra_filter'>
	<ul>
		<li>
			<label for='forums_filter'>{$this->lang->words['find_forum']}:</label>
			<select name='search_app_filters[forums][forums][]' class='input_select' size='6' multiple='multiple'>
				{$forums}
			</select>
		</li>
		" . (($this->settings['search_method'] != 'sphinx') ? ("
		<li>
			<label>&nbsp;</label>
			<input id='f_content_only' type='checkbox' name='search_app_filters[forums][contentOnly]' class='input_checkbox' value='1' /> {$this->lang->words['s_search_posts']}
		</li>
		<li>
			<label>&nbsp;</label>
			<input id='noPreview' type='checkbox' name='search_app_filters[forums][noPreview]' class='input_checkbox' value='1' /> {$this->lang->words['s_show_topics_only']}
		</li>
		<li>
			<label for='f_p_data'>{$this->lang->words['s_forum_stuff']} </label>
			" . sprintf( $this->lang->words['s_forum_stuff_2'], "<input id='f_p_count' type='text' name='search_app_filters[forums][pCount]' class='input_text' style='vertical-align: middle; width:40px' size='5' value='' />", "<input id='f_p_views' type='text' name='search_app_filters[forums][pViews]' class='input_text' style='vertical-align: middle; width:40px' size='5' value='' />") . "
		</li>
		") : ("")) . "
	</ul>
</fieldset>";
return $IPBHTML;
}

/* -- forumSearchResult --*/
function forumSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<result>
	<icon>{$this->settings['public_dir']}style_extra/app_icons/comments.png</icon>
	<type>Forum</type>
	<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$r['type_id']}", 'public','' ), "", "" ) . "</url>
	<title><![CDATA[{$r['content_title']}]]></title>
	<content><![CDATA[{$r['content']}]]></content>
	<date>" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . "</date>
	<user>
		<id>{$r['member_id']}</id>
		<name>{$r['members_display_name']}</name>
		<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "", "" ) . "</url>
	</user>
</result>";
return $IPBHTML;
}

/* -- galleryCommentSearchResult --*/
function galleryCommentSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<result>
	<icon>{$this->settings['public_dir']}style_extra/app_icons/gallery.png</icon>
	<type>Gallery Comment</type>
	<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=images&amp;img={$r['misc']}&amp;hl={$this->request['search_term']}", 'public','' ), "", "" ) . "</url>
	<title><![CDATA[{$r['content_title']}]]></title>
	<content><![CDATA[{$r['content']}]]></content>
	<date>" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . "</date>
	<user>
		<id>{$r['member_id']}</id>
		<name>{$r['members_display_name']}</name>
		<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "", "" ) . "</url>
	</user>
</result>";
return $IPBHTML;
}

/* -- galleryImageSearchResult --*/
function galleryImageSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<div class='result_info'>
	<span class='icon'>{$r['image']}</span>
	
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=images&amp;section=viewimage&amp;img={$r['type_id_2']}", 'public','' ), "", "" ) . "'>{$r['content_title']}</a></h3>
	" . ((!$resultAsTitle) ? ("
		<p>
			{$r['content']}
		</p>
	") : ("")) . "
</div>
<div class='result_details desc'>
	<ul>
		<li>{$r['comments']} {$this->lang->words['gallery_comments']}</li>
		<li>" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . "</li>
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id'], $r['members_seo_name']) . "</li>
	</ul>
</div>";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<div class='result_info'>
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help&amp;do=01&amp;HID={$r['type_id_2']}&amp;hl={$this->request['search_higlight']}", 'public','' ), "", "" ) . "'>{$r['content_title']}</a></h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['content']}
	</p>
	") : ("")) . "
</div>";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "" . ((!$resultAsTitle) ? ("<span class='icon'>
		" . (($r['misc']['pp_thumb_photo']) ? ("
			<img src='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "/{$r['misc']['pp_thumb_photo']}", 'upload','' ), "", "" ) . "' class='photo' />
		") : ("
			<img src='{$this->settings['img_url']}/profile/default_thumb.png' class='photo' />
		")) . "
	</span>") : ("")) . "
<div class='result_info'>
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['type_id_2']}", 'public','' ), "{$r['members_seo_name']}", "" ) . "'>{$r['content_title']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['type_id_2'],$r['members_seo_name']) . "</h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['misc']['pp_bio_content']}
	</p>
	") : ("")) . "
	<span class='desc breadcrumb'>
		{$this->lang->words['member_joined']} " . $this->registry->getClass('class_localization')->getDate($r['joined'],"short", 0) . "
	</span>
</div>";
return $IPBHTML;
}

/* -- newPostsView --*/
function newPostsView($results, $pagination, $total, $asForum=false) {
$IPBHTML = "";

$this->registry->templateStriping['searchStripe'] = array( FALSE, "row1","row2");
$IPBHTML .= "<h2>{$this->lang->words['new_content']}</h2>
" . (($total) ? ("
	<p class='message'>
		{$this->lang->words['new_content_there']} <strong>{$total}</strong> {$this->lang->words['new_content_entries']}
	</p>
	<br />
	<div class='topic_controls'>
		{$pagination}
	</div>
") : ("")) . "
<ol id='member_alpha' class='tab_bar'>
	" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("" . ((isset( $this->request['search_filter_app'] ) && $this->request['search_filter_app']['all'] != 1) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=new_posts&amp;search_filter_app[all]=1", 'public','' ), "", "" ) . "'>{$this->lang->words['new_content_all']}</a></li>
		") : ("
			<li class='active'><strong>{$this->lang->words['new_content_all']}</strong></li>
		")) . "") : ("")) . "
	".$this->__f__4b9a03b7467cb954ed8ba5114cc5afbd($results,$pagination,$total,$asForum)."</ol>
<div class='tab_filters'>
	<ul class='right padded'>
		<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=all&amp;k={$this->member->form_hash}", 'public','' ), "", "" ) . "\" title='{$this->lang->words['mark_all_as_read']}'>{$this->lang->words['s_mark_all_read']}</a>
	</ul>
</div>
" . (($total) ? ("" . (($asForum) ? ("
		<table class='ipb_table topic_list' id='forum_table'>
			<tr class='header'>
				<th scope='col' class='col_f_icon'>&nbsp;</th>
				<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
				<th scope='col' class='col_f_starter'>{$this->lang->words['forum_forum']}</th>
				<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
				<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
				<th scope='col' class='col_f_post'>{$this->lang->words['forum_last_post_info']}</th>
			</tr>
			".$this->__f__ed87e61d5128a8a29c8910b1a2c66545($results,$pagination,$total,$asForum)."		</table>
	") : ("
				<div id='search_results'>
			<ol>
				".$this->__f__732264eee83d041ecc933bc9531bc2cf($results,$pagination,$total,$asForum)."			</ol>
		</div>
	")) . "
	{$pagination}") : ("
	<p class='no_messages'>{$this->lang->words['new_content_none']}</p>
")) . "";
return $IPBHTML;
}


function __f__4b9a03b7467cb954ed8ba5114cc5afbd($results, $pagination, $total, $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $this->registry->getApplications() as $app )
	{
		
		$_ips___x_retval .= "
		" . ((IPSSearchIndex::appIsSearchable( $app['app_directory'] )) ? ("" . (($this->request['search_app'] == $app['app_directory']) ? ("<li class='active'><strong>" . ((strtolower($app['app_title']) == 'system') ? ("{$this->lang->words['livesearch_helpfiles']}") : ("" . IPSLib::getAppTitle( $app['app_directory'] ) . "")) . "</strong></li>") : ("<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=new_posts&amp;search_filter_app[{$app['app_directory']}]=1", 'public','' ), "", "" ) . "'>" . ((strtolower($app['app_title']) == 'system') ? ("{$this->lang->words['livesearch_helpfiles']}") : ("" . IPSLib::getAppTitle( $app['app_directory'] ) . "")) . "</a></li>")) . "") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__ed87e61d5128a8a29c8910b1a2c66545($results, $pagination, $total, $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "
				{$result['html']}
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__732264eee83d041ecc933bc9531bc2cf($results, $pagination, $total, $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "	
					" . (($result['sub']) ? ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " sub clear clearfix'>
							{$result['html']}
						</li>
					") : ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " clear clearfix'>
							{$result['html']}
						</li>
					")) . "
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $removed_search_terms=array()) {
$IPBHTML = "";
$IPBHTML .= "<style type='text/css'>
 	@import url('{$this->settings['public_dir']}/style_css/{$this->registry->output->skin['_csscacheid']}/calendar_select.css');
</style>
<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/calendar_date_select/calendar_date_select.js'></script>
" . $this->registry->getClass('output')->addJSModule("search", "0" ) . "
<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;section=search&amp;do=quick_search&amp;search_app={$this->registry->getCurrentApplication()}", 'public','' ), "", "" ) . "&amp;fromsearch=1\" method=\"post\" id='search-box' >
<input type='hidden' name='search_filter_app[all]' value='1' />
<p class='message'>
	<strong>{$this->lang->words['optional_fields']}</strong>
</p>
" . ((is_array( $removed_search_terms ) && count( $removed_search_terms )) ? ("
<br />
<p class='message error'>{$this->lang->words['removed_search_terms']} <strong>" . implode( ',', $removed_search_terms ) . "</strong></p>
") : ("")) . "
" . (($msg) ? ("
<br />
<p class='message error'>{$msg}</p>
") : ("")) . "
<br />
<h2 class='maintitle'>{$this->lang->words['search']}</h2>
<div id='main_search_form' class='clear'>
	
	<div id='search_info' class='row1'>
		<div class='generic_bar'></div>
		<fieldset id='main_search' class='row2'>
			<ul>
				<li>
					<label for='query'>{$this->lang->words['find_words']}:</label>
					<input type='text' class='input_text' name='search_term' id='query' value='{$this->request['search_term']}' /><br />
				</li>
					<li>
					<!--SKINNOTE: This isn't semantic - the text for the checkbox should be wrapped in the label, and label should be \"for\" the element-->
						<label>&nbsp;</label>
						<input type='checkbox' class='input_check' name='content_title_only' value='1'> {$this->lang->words['search_titles_only']}
						" . (($this->settings['enable_show_as_titles']) ? ("
							<br /><label>&nbsp;</label>
							<input type='checkbox' class='input_check' name='show_as_titles' value='1'> {$this->lang->words['show_as_titles']}
						") : ("")) . "
					</li>
					<li>
						<label for='search_by'>{$this->lang->words['s_search_type']}</label>
						<select name='search_sort_by' id='search_sort_by' class='input_select' style='width:auto'>
							<option value='0' " . ((!$this->request['search_sort_by']) ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_0']}</option>
							<option value='1' " . (($this->request['search_sort_by']) ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_1']}</option>
						</select>
						<select name='search_sort_order' id='search_sort_order' class='input_select' style='width:auto'>
							<option value='0' " . ((!$this->request['search_sort_order']) ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_o_0']}</option>
							<option value='1' " . (($this->request['search_sort_order']) ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_o_1']}</option>
						</select>
					</li>
				<li>
					<label for='author'>{$this->lang->words['find_author']}:</label>
					<input type='text' class='input_text' name='search_author' id='author' value='{$this->request['search_author']}' />
				</li>
				<li>			
					<label for='date_start'>{$this->lang->words['find_date']}:</label>
					<input type='text' class='input_text date' name='search_date_start' id='date_start' value='{$this->request['_search_date_start']}' /><img src='{$this->settings['img_url']}/date.png' alt='{$this->lang->words['icon']}' id='date_start_icon' style='cursor: pointer' /> &nbsp;
					<strong>{$this->lang->words['to']}</strong> &nbsp;<input type='text' class='input_text date' name='search_date_end' id='date_end' value='{$this->request['_search_date_end']}' /><img src='{$this->settings['img_url']}/date.png' alt='{$this->lang->words['icon']}' id='date_end_icon' style='cursor: pointer' />
				</li>
			</ul>
		</fieldset>
		{$filters}
		<fieldset class='submit'>
			<input type='submit' name='submit' class='input_submit' value='{$this->lang->words['do_search']}'> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
		</fieldset>
	</div>
</div>
</form>
<script type='text/javascript'>
	ipb.search.initSearchForm();
</script>";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $asForum=false) {
$IPBHTML = "";

$sort_url_string = preg_replace( '#search_sort_by=(\w+?)?&#', '&', $url_string );
				$sort_url_string = preg_replace( '#search_sort_order=(\w+?)?&#', '&', $sort_url_string );

$this->registry->templateStriping['forumTable'] = array( FALSE, "row1","row2");

$this->registry->templateStriping['searchStripe'] = array( FALSE, "row1","row2");
$IPBHTML .= "<h2 class='hide'>{$this->lang->words['search_results']}</h2>
" . ((is_array( $removed_search_terms ) && count( $removed_search_terms )) ? ("
<p class='message error'>{$this->lang->words['removed_search_terms']} <strong>" . implode( ',', $removed_search_terms ) . "</strong></p>
<br />
") : ("")) . "
	" . (($total > 0 AND $search_term != '') ? ("
		<p class='message'>
			{$this->lang->words['your_search']} <em><strong>{$search_term}</strong></em> {$this->lang->words['your_search_returned']} <strong>{$total}</strong> {$this->lang->words['your_search_results']}
		</p>
	") : ("")) . "
	<br />
	<div class='topic_controls'>
		{$pagination}
	</div>
	
	<ol id='member_alpha' class='tab_bar'>
		" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("" . (($this->request['search_filter_app']['all'] != 1) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url_string}", 'public','' ), "", "" ) . "'>{$this->lang->words['my_results']}</a></li>
			") : ("
				<li class='active'><strong>{$this->lang->words['my_results']}</strong></li>
			")) . "") : ("")) . "
		
		<!--harcoded forums, members, system apps-->
		" . ((isset( $this->request['search_filter_app']['forums'] ) && $this->request['search_filter_app']['forums'] == 1) ? ("
			<li class='active'><strong>{$this->lang->words['search_tab_forums']}</strong></li>
		") : ("				
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url_string}&amp;search_filter_app[forums]=1", 'public','' ), "", "" ) . "'>{$this->lang->words['search_tab_forums']}</a></li>
		")) . "
		" . ((isset( $this->request['search_filter_app']['members'] ) && $this->request['search_filter_app']['members'] == 1) ? ("
			<li class='active'><strong>{$this->lang->words['search_tab_members']}</strong></li>
		") : ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url_string}&amp;search_filter_app[members]=1", 'public','' ), "", "" ) . "'>{$this->lang->words['search_tab_members']}</a></li>
		")) . "
		" . ((isset( $this->request['search_filter_app']['core'] ) && $this->request['search_filter_app']['core'] == 1) ? ("
			<li class='active'><strong>{$this->lang->words['livesearch_helpfiles']}</strong></li>
		") : ("				
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url_string}&amp;search_filter_app[core]=1", 'public','' ), "", "" ) . "'>{$this->lang->words['livesearch_helpfiles']}</a></li>
		")) . "
		".$this->__f__1ba55e8acf1e6740c375a4e77047e665($results,$pagination,$total,$showing,$search_term,$url_string,$current_key,$removed_search_terms,$asForum)."	</ol>
	<div class='tab_filters'>
		<ul class='right'>
						<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$sort_url_string}&amp;search_sort_by=relevence&amp;search_filter_app[{$current_key}]=1", 'public','' ), "", "" ) . "' method='post'>
			<label for='search_by'>{$this->lang->words['s_search_type']}</label>
			<select name='search_sort_by' id='search_sort_by' class='input_select' style='width:auto'>
				<option value='0' " . (($this->request['search_sort_by'] == 'date') ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_0']}</option>
				<option value='1' " . (($this->request['search_sort_by'] == 'relevance') ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_1']}</option>
			</select>
			<select name='search_sort_order' id='search_sort_order' class='input_select' style='width:auto'>
				<option value='0' " . (($this->request['search_sort_order'] == 'desc') ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_o_0']}</option>
				<option value='1' " . (($this->request['search_sort_order'] == 'asc') ? ("selected='selected'") : ("")) . ">{$this->lang->words['s_search_type_o_1']}</option>
			</select>
			<input type='submit' class='input_submit alt' value='{$this->lang->words['s_update']}' />
			</form>
		</ul>
	</div>
	
" . (($total) ? ("" . (($asForum) ? ("<table class='ipb_table topic_list' id='forum_table'>
			<tr class='header'>
				<th scope='col' class='col_f_icon'>&nbsp;</th>
				<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
				<th scope='col' class='col_f_starter'>{$this->lang->words['forum_forum']}</th>
				<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
				<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
				<th scope='col' class='col_f_post'>" . (($this->request['content_title_only'] OR $this->request['show_as_titles']) ? ("{$this->lang->words['forum_last_post_info']}") : ("{$this->lang->words['forum_showas_post_info']}")) . "</th>
			</tr>
						".$this->__f__22220e6db8c04e526fd4594cee67eab4($results,$pagination,$total,$showing,$search_term,$url_string,$current_key,$removed_search_terms,$asForum)."		</table>") : ("
				<div id='search_results'>
			<ol>
				".$this->__f__3dc483a2337c8f628ed357066d372dc5($results,$pagination,$total,$showing,$search_term,$url_string,$current_key,$removed_search_terms,$asForum)."			</ol>
		</div>
	")) . "
	<br />
	<div class='topic_controls'>
		{$pagination}
	</div>") : ("<p class='no_messages'>{$this->lang->words['no_results_found']}" . (($search_term) ? (" {$this->lang->words['no_results_found_for']} '{$search_term}'") : ("")) . ".</p>")) . "";
return $IPBHTML;
}


function __f__1ba55e8acf1e6740c375a4e77047e665($results, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $this->registry->getApplications() as $app )
	{
		
		$_ips___x_retval .= "
			" . ((IPSSearchIndex::appIsSearchable( $app['app_directory'] ) AND !in_array( $app['app_directory'], array('core','forums','members') )) ? ("" . ((isset( $this->request['search_filter_app'][$app['app_directory']] ) && $this->request['search_filter_app'][$app['app_directory']] == 1) ? ("
					<li class='active'><strong>" . IPSLib::getAppTitle( $app['app_directory'] ) . "</strong></li>
				") : ("				
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url_string}&amp;search_filter_app[{$app['app_directory']}]=1", 'public','' ), "", "" ) . "'>" . IPSLib::getAppTitle( $app['app_directory'] ) . "</a></li>
				")) . "") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__22220e6db8c04e526fd4594cee67eab4($results, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "
				{$result['html']}
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__3dc483a2337c8f628ed357066d372dc5($results, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $asForum=false)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "	
					" . (($result['sub']) ? ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " sub clearfix clear'>
							{$result['html']}
						</li>
					") : ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " clearfix clear'>
							{$result['html']}
						</li>
					")) . "
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- SKINNOTE: Wrap user link in ajax span -->
<div class='result_info'>
	<h3>{$r['content_title']}</h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['content']}
	</p>
	") : ("")) . "
</div>
<div class='result_details desc'>
	<ul>
		<li>" . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . "</li>
		<li>{$this->lang->words['search_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id']) . "</li>
	</ul>
</div>";
return $IPBHTML;
}

/* -- topicPostSearchResult --*/
function topicPostSearchResult($r, $indent, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<div class='result_info'>
	<span class='icon'>" . $this->registry->getClass('output')->getReplacement("{$r['_icon']}") . "</span>
	<h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($r['misc']) ? ("findpost&amp;p={$r['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", 'public','' ), "{$r['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_result']}'>{$r['content_title']}</a></h3>
	" . ((!$resultAsTitle) ? ("
	<p>
		{$r['content']}
	</p>
	") : ("")) . "
	" . (($r['_forum_trail']) ? ("
		<span class='desc breadcrumb'>
			".$this->__f__ae4b6f5e5225de2955013847e74cd7e0($r,$indent,$resultAsTitle)."		</span>
	") : ("")) . "
</div>
<div class='result_details desc'>
	<ul>
		<li>" . $this->registry->getClass('class_localization')->formatNumber( $r['posts'] ) . " {$this->lang->words['forum_replies']}</li>
		<li>
			" . (($resultAsTitle) ? ("
				" . $this->registry->getClass('class_localization')->getDate($r['_last_post'],"short", 0) . " {$this->lang->words['search_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['last_poster_id']}", 'public','' ), "{$r['seo_last_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['last_poster_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['last_poster_id'], $r['seo_last_name']) . "
			") : ("
				" . $this->registry->getClass('class_localization')->getDate($r['_post_date'],"short", 0) . " {$this->lang->words['search_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", 'public','' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($r['member_id'], $r['members_seo_name']) . "
			")) . "
		</li>
		" . (($r['topic_hasattach']) ? ("
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=attach&amp;tid={$r['type_id_2']}", 'public','' ), "", "" ) . "\">{$r['topic_hasattach']} {$this->lang->words['attach_header']}</a></li>
		") : ("")) . "
	</ul>
</div>";
return $IPBHTML;
}


function __f__ae4b6f5e5225de2955013847e74cd7e0($r, $indent, $resultAsTitle=false)
{
	$_ips___x_retval = '';
	foreach( $r['_forum_trail'] as $i => $f )
	{
		
		$_ips___x_retval .= "
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$f[1]}", 'public','' ), "{$f[2]}", "showforum" ) . "'>{$f[0]}</a> " . (($i+1 != count( $r['_forum_trail'] )) ? ("&gt;") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $childEntry=0, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<tr class='" .  IPSLib::next( $this->registry->templateStriping["forumTable"] ) . "' id='trow_{$data['tid']}'>
	<td class='short altrow'>" . $this->registry->getClass('output')->getReplacement("{$data['_icon']}") . "</td>
	<td>
		{$data['prefix']}
		" . (($data['topic_hasattach']) ? ("
			<!-- SKINNOTE: This is the link for the attachments popup  -->
			<a href=\"{$this->settings['base_url']}app=forums&amp;module=forums&amp;section=attach&amp;tid={$data['tid']}\" title=\"" . intval($data['topic_hasattach']) . " {$this->lang->words['topic_attach']}\">" . $this->registry->getClass('output')->getReplacement("t_attach") . "</a>
		") : ("")) . "
		" . ((!$resultAsTitle) ? ("
			<strong>
		") : ("")) . "
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "' title='" . (($data['_shortTitle'] != $data['_longTitle']) ? ("{$data['_longTitle']}") : ("{$this->lang->words['view_result']}")) . "'>{$data['_shortTitle']}</a>
		" . ((!$resultAsTitle) ? ("
			</strong>
		") : ("")) . "
		" . ((isset( $data['pages'] ) AND is_array( $data['pages'] ) AND count( $data['pages'] )) ? ("
			<ul class='mini_pagination'>
			".$this->__f__1945faa383209d4cbfc527a889f7b354($data,$childEntry,$resultAsTitle)."			</ul>
		") : ("")) . "
		" . (($data['description']) ? ("<br /><span class='desc'>{$data['description']}</span>") : ("")) . "
		" . ((!$resultAsTitle) ? ("
			<div class='message unspecific' style='background-image:none;padding-left:10px'>
				<div style=\"width:30px;float:left\"><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;view=findpost&amp;p={$data['pid']}", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "\">" . $this->registry->getClass('output')->getReplacement("snapback") . "</a></div>
				{$data['content']}
				<p class='desc' style='font-size:0.8em'><em>" . sprintf( $this->lang->words['sr_as_post_string'], $data['post_date'], $data['members_display_name'] ) . "</em></p>
			</div>
		") : ("")) . "
	</td>
	<td class='altrow'>
		".$this->__f__de2ad6ec014f482928a8f4f636d151ff($data,$childEntry,$resultAsTitle)."	</td>
	<td class='short'>{$data['starter']}" . $this->registry->getClass('output')->getTemplate('global')->user_popup($data['starter_id'], $data['seo_first_name']) . "</td>
	<td class='stats altrow'>
		<ul>
			<li>" . $this->registry->getClass('class_localization')->formatNumber( $data['posts'] ) . " " . ((intval($data['posts']) == 1) ? ("{$this->lang->words['reply']}") : ("{$this->lang->words['replies']}")) . "</li>
			<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $data['views'] ) . " {$this->lang->words['views']}</li>
		</ul>
	</td>
	<td>
		<ul class='last_post'>
			<li>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;view=getlastpost", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['goto_last_post']}'>" . $this->registry->getClass('output')->getReplacement("f_lastpost") . "</a> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;view=getlastpost", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['goto_last_post']}'>" . (($resultAsTitle) ? ("{$data['last_post']}") : ("{$data['post_date']}")) . "</a>
			</li>
			<li>{$this->lang->words['forum_by']} " . (($resultAsTitle) ? ("{$data['last_poster']}" . $this->registry->getClass('output')->getTemplate('global')->user_popup($data['last_poster_id'], $data['seo_last_name']) . "") : ("{$data['members_display_name']}" . $this->registry->getClass('output')->getTemplate('global')->user_popup($data['member_id'], $data['members_seo_name']) . "")) . "</li>
		</ul>
	</td>
</tr>";
return $IPBHTML;
}


function __f__1945faa383209d4cbfc527a889f7b354($data, $childEntry=0, $resultAsTitle=false)
{
	$_ips___x_retval = '';
	foreach( $data['pages'] as $page )
	{
		
		$_ips___x_retval .= "
					" . (($page['last']) ? ("
						<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;st={$page['st']}", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']} &rarr;</a></li>
					") : ("
						<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;st={$page['st']}", 'public','' ), "{$data['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']}</a></li>
					")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__de2ad6ec014f482928a8f4f636d151ff($data, $childEntry=0, $resultAsTitle=false)
{
	$_ips___x_retval = '';
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$_ips___x_retval .= "
		" . (($i+1 == count( $data['_forum_trail'] )) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$f[1]}", 'public','' ), "{$f[2]}", "showforum" ) . "'>{$f[0]}</a>") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- topicPostSubresultWrap --*/
function topicPostSubresultWrap($content) {
$IPBHTML = "";
$IPBHTML .= "<ol>
		{$content}
	</ol>";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $asForum) {
$IPBHTML = "";

$this->registry->templateStriping['searchStripe'] = array( FALSE, "row1","row2");
$IPBHTML .= "<h2>{$this->lang->words['user_posts_title_all']} " . (($this->request['view_by_title'] && $this->request['search_app'] == 'forums') ? ("{$this->lang->words['user_posts_title_topics']}") : ("{$this->lang->words['user_posts_title_posts']}")) . " {$this->lang->words['user_posts_title_member']} {$member['members_display_name']}</h2>
" . (($total) ? ("<p class='message'>
		{$this->lang->words['user_posts_have_been']} <em><strong>{$total}</strong></em> " . (($this->request['view_by_title'] && $this->request['search_app'] == 'forums') ? ("{$this->lang->words['user_posts_title_topics']}") : ("{$this->lang->words['user_posts_title_posts']}")) . " {$this->lang->words['user_posts_title_member']} {$member['members_display_name']}
	</p>
	<br />") : ("")) . "
<div class='topic_controls'>
	{$pagination}
</div>
<ol id='member_alpha' class='tab_bar no_title'>
	" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("" . ((isset( $this->request['search_filter_app'] ) && $this->request['search_filter_app']['all'] != 1) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$this->request['mid']}&amp;search_filter_app[all]=1&amp;view_by_title={$this->request['view_by_title']}", 'public','' ), "", "" ) . "'>{$this->lang->words['user_posts_all']}</a></li>
		") : ("
			<li class='active'><strong>{$this->lang->words['user_posts_all']}</strong></li>
		")) . "") : ("")) . "
	".$this->__f__5a7ebe6bc5183db0c5626ed395e2e65d($results,$pagination,$total,$member,$asForum)."</ol>
" . (($total) ? ("" . (($asForum) ? ("
		<table class='ipb_table topic_list' id='forum_table'>
			<tr class='header'>
				<th scope='col' class='col_f_icon'>&nbsp;</th>
				<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
				<th scope='col' class='col_f_starter'>{$this->lang->words['forum_forum']}</th>
				<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
				<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
				<th scope='col' class='col_f_post'>{$this->lang->words['forum_last_post_info']}</th>
			</tr>
			".$this->__f__817a04591a05d2f5eb9033b0f4d25dd1($results,$pagination,$total,$member,$asForum)."		</table>
	") : ("
				<div id='search_results'>
			<ol>
				".$this->__f__6bb44215d3fddd5d7fbc0a09aa347dd9($results,$pagination,$total,$member,$asForum)."			</ol>
		</div>
	")) . "") : ("
	<p class='no_messages'>{$this->lang->words['user_posts_none']}</p>
")) . "
<br />
<div class='topic_controls'>
	{$pagination}
</div>";
return $IPBHTML;
}


function __f__5a7ebe6bc5183db0c5626ed395e2e65d($results, $pagination, $total, $member, $asForum)
{
	$_ips___x_retval = '';
	foreach( $this->registry->getApplications() as $app )
	{
		
		$_ips___x_retval .= "
		" . ((IPSSearchIndex::appIsSearchable( $app['app_directory'] ) && ! in_array( $app['app_directory'], array( 'core', 'members' ) )) ? ("" . (($this->request['search_app'] == $app['app_directory']) ? ("
				<li class='active'><strong>" . IPSLib::getAppTitle( $app['app_directory'] ) . "</strong></li>
			") : ("				
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$this->request['mid']}&amp;search_filter_app[{$app['app_directory']}]=1&amp;view_by_title={$this->request['view_by_title']}", 'public','' ), "", "" ) . "'>" . IPSLib::getAppTitle( $app['app_directory'] ) . "</a></li>
			")) . "") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__817a04591a05d2f5eb9033b0f4d25dd1($results, $pagination, $total, $member, $asForum)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "
				{$result['html']}
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__6bb44215d3fddd5d7fbc0a09aa347dd9($results, $pagination, $total, $member, $asForum)
{
	$_ips___x_retval = '';
	foreach( $results as $result )
	{
		
		$_ips___x_retval .= "	
					" . (($result['sub']) ? ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " sub clearfix clear'>
							{$result['html']}
						</li>
					") : ("
						<li class='" .  IPSLib::next( $this->registry->templateStriping["searchStripe"] ) . " clearfix clear'>
							{$result['html']}
						</li>
					")) . "
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>