<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:03 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_profile_1 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- customField__gender --*/
function customField__gender($f) {
$IPBHTML = "";
$IPBHTML .= "<dt>{$f->raw_data['pf_title']}:</dt>
<dd>
" . (($f->value) ? ("" . (($f->value == 'm') ? ("
		<img src='{$this->settings['img_url']}/profile/male.png' alt='{$this->lang->words['js_gender_male']}' /> {$this->lang->words['js_gender_male']}
	") : ("")) . "
	
	" . (($f->value == 'f') ? ("
		<img src='{$this->settings['img_url']}/profile/female.png' alt='{$this->lang->words['js_gender_female']}' /> {$this->lang->words['js_gender_female']}
	") : ("")) . "
	
	" . (($f->value =='u') ? ("
		<img src='{$this->settings['img_url']}/profile/mystery.png' alt='{$this->lang->words['js_gender_mystery']}' /> {$this->lang->words['js_gender_mystery']}
	") : ("")) . "") : ("
	{$this->lang->words['m_no_gender']}
")) . "
</dd>";
return $IPBHTML;
}

/* -- customField__generic --*/
function customField__generic($f) {
$IPBHTML = "";
$IPBHTML .= "" . (($f->parsed != '') ? ("<dt>{$f->raw_data['pf_title']}:</dt>
	<dd>
		" . ((is_array($f->parsed)) ? ("
			" . implode( '<br />', $f->parsed ) . "
		") : ("
			{$f->parsed}
		")) . "
	</dd>") : ("")) . "";
return $IPBHTML;
}

/* -- customFieldGroup__contact --*/
function customFieldGroup__contact($f) {
$IPBHTML = "";
$IPBHTML .= "" . (($f->parsed) ? ("<dt>{$f->raw_data['pf_title']}:</dt>
<dd>
	" . (($f->raw_data['pf_icon']) ? ("<img src='{$this->settings['public_dir']}{$f->raw_data['pf_icon']}' alt='{$f->raw_data['pf_title']}' />&nbsp;") : ("")) . "
	" . ((is_array( $f->parsed )) ? ("
		".$this->__f__04b6e3a0f7b89b0f06f9793d06d1f114($f)."	") : ("" . (($f->raw_data['pf_key'] == 'aim') ? ("
			<a class='url' href='aim:goim?screenname={$f->parsed}'>{$f->parsed}</a>
		") : ("" . (($f->raw_data['pf_key'] == 'msn') ? ("
				<a class='url' href='msnim:chat?contact={$f->parsed}'>{$f->parsed}</a>
			") : ("" . (($f->raw_data['pf_key'] == 'yahoo') ? ("
					<a class='url' href='ymsgr:sendIM?{$f->parsed}'>{$f->parsed}</a>
				") : ("" . (($f->raw_data['pf_key'] == 'icq') ? ("
						<a class='url' type=\"application/x-icq\" href='http://www.icq.com/people/cmd.php?uin={$f->parsed}&amp;action=message'>{$f->parsed}</a>
					") : ("" . (($f->raw_data['pf_key'] == 'website') ? ("
							<a class='url uid' rel=\"me\" href='{$f->parsed}'>{$f->parsed}</a>
						") : ("" . (($f->raw_data['pf_key'] == 'jabber') ? ("
								<a class='url' href='xmpp:{$f->parsed}'>{$f->parsed}</a>
							") : ("" . (($f->raw_data['pf_key'] == 'skype') ? ("
									<a class='url' href='skype:{$f->parsed}?call'>{$f->parsed}</a>
								") : ("
									{$f->parsed}
								")) . "")) . "")) . "")) . "")) . "")) . "")) . "")) . "
</dd>") : ("")) . "";
return $IPBHTML;
}


function __f__04b6e3a0f7b89b0f06f9793d06d1f114($f)
{
	$_ips___x_retval = '';
	foreach( $f->parsed as $value )
	{
		
		$_ips___x_retval .= "
			{$value}
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- dnameWrapper --*/
function dnameWrapper($member_name="",$records=array()) {
$IPBHTML = "";

$this->registry->templateStriping['dname'] = array( FALSE, "row1","row2");
$IPBHTML .= "" . (($this->request['module']=='ajax') ? ("
	<h3>{$this->lang->words['dname_window_title']} {$member_name}</h3>
") : ("
	<h3 class='maintitle'>{$this->lang->words['dname_window_title']} {$member_name}</h3>
")) . "
<table class='ipb_table'>
	<tr class='header'>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_name_from']}</th>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_name_to']}</th>
		<th scope='col' style='width: 33%'>{$this->lang->words['dname_date']}</th>
	</tr>
	" . ((is_array($records) AND count($records)) ? ("
		    	".$this->__f__ba34405eb6ba2b0edfdbc7d6c68eb310($member_name,$records)."	") : ("
		<tr>
			<td colspan='3' class='no_messages'>{$this->lang->words['dname_no_history']}</td>
		</tr>
    ")) . "
</table>";
return $IPBHTML;
}


function __f__ba34405eb6ba2b0edfdbc7d6c68eb310($member_name="",$records=array())
{
	$_ips___x_retval = '';
	foreach( $records as $row )
	{
		
		$_ips___x_retval .= "
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["dname"] ) . "'>
		 	<td>{$row['dname_previous']}</td>
		 	<td><strong>{$row['dname_current']}</strong></td>
		 	<td class='altrow'>" . $this->registry->getClass('class_localization')->getDate($row['dname_date'],"short", 0) . "</td>
		</tr>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- friendsIframe --*/
function friendsIframe($member, $friends, $showWrapper=false) {
$IPBHTML = "";
$IPBHTML .= "" . (($showWrapper) ? ("
		<div class='friend_list'>
	") : ("")) . "
		<h3 class='bar'>Friends</h3>
		" . ((is_array($friends) and count($friends)) ? ("
			<ul>
			".$this->__f__8b20cf7e4bd661b6ae01bc386df69bb0($member,$friends,$showWrapper)."			</ul>
		") : ("
			<p>
				<em>{$member['members_display_name']} {$this->lang->words['no_friends_yet']}</em>
			</p>
		")) . "
	" . (($showWrapper) ? ("
		</div>
	") : ("")) . "";
return $IPBHTML;
}


function __f__8b20cf7e4bd661b6ae01bc386df69bb0($member, $friends, $showWrapper=false)
{
	$_ips___x_retval = '';
	foreach( $friends as $friend )
	{
		
		$_ips___x_retval .= "
				<li>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_display_name_short']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' ><img src='{$friend['pp_thumb_photo']}' width='{$friend['pp_thumb_width']}' height='{$friend['pp_thumb_height']}' alt='Photo' class='photo' /></a><br />
					<span class='name'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name_short']}</a> " . $this->registry->getClass('output')->getTemplate('global')->user_popup($friend['member_id'], $friend['members_seo_name']) . "</span>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- friendsList --*/
function friendsList($friends, $pages) {
$IPBHTML = "";

$this->registry->templateStriping['memberStripe'] = array( FALSE, "row1","row2");
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("friends", "0" ) . "
<h2>{$this->lang->words['m_friends_list']}</h2>
" . (($pages) ? ("
	<div class='topic_controls'>
		$pages
	</div>
") : ("")) . "
<ul class='tab_bar no_title'>
	" . (($this->request['tab'] == 'list' || !$this->request['tab']) ? ("
		<li class='active'><strong>{$this->lang->words['m_friends_list']}</strong></li>
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=pending", 'public','' ), "", "" ) . "' title='{$this->lang->words['m_friends_pending']}'>{$this->lang->words['m_friends_pending']}</a></li>
	") : ("")) . "
	" . (($this->request['tab'] == 'pending') ? ("
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=list&amp;tab=list", 'public','' ), "", "" ) . "' title='{$this->lang->words['m_friends_list']}'>{$this->lang->words['m_friends_list']}</a></li>
		<li class='active'><strong>{$this->lang->words['m_friends_pending']}</strong></li>
	") : ("")) . "
</ul>
" . ((is_array($friends) and count($friends) && $this->settings['friends_enabled']) ? ("
		<ul class='members'>
	".$this->__f__501b78152478fd9c46d4a3303397bf5e($friends,$pages)."	</ul>
") : ("<p class='no_messages'>
		" . (($this->request['tab'] == 'pending') ? ("
			{$this->lang->words['no_friends_awaiting_approval']}
		") : ("
			{$this->lang->words['no_friends_to_display']}
		")) . "
	</p>")) . "
" . (($pages) ? ("
	<div class='topic_controls'>
		$pages
	</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__501b78152478fd9c46d4a3303397bf5e($friends, $pages)
{
	$_ips___x_retval = '';
	foreach( $friends as $friend )
	{
		
		$_ips___x_retval .= "
		" . (($this->request['tab'] == 'pending') ? ("<li id='member_id_{$friend['member_id']}' class='general_box clear member_entry " .  IPSLib::next( $this->registry->templateStriping["memberStripe"] ) . "'>
				<h3 class='bar'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['friends_member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($friend['member_id'],$friend['members_seo_name']) . "</h3>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><img src='{$friend['pp_thumb_photo']}' width='{$friend['pp_thumb_width']}' height='{$friend['pp_thumb_height']}' alt=\"{$friend['members_display_name']}{$this->lang->words['users_photo']}\" class='photo' /></a>	
			
				<dl class='info'>
					<dt class='clear'>{$this->lang->words['m_member_since']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->getDate($friend['joined'],"short", 0) . "</dd>
					<dt class='clear'>{$this->lang->words['m_group']}</dt>
					<dd>{$friend['_group_formatted']}</dd>
					<dt class='clear'>{$this->lang->words['m_posts']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->formatNumber( $friend['posts'] ) . "</dd>
					<dt class='clear'>{$this->lang->words['m_last_active']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->getDate($friend['last_activity'],"short", 0) . "</dd>
				</dl>
				
				<ul class='user_controls clear'>
					<li class='positive'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=moderate&amp;pp_option=approve&amp;pp_friend_id[{$friend['member_id']}]=1&amp;md5check={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='Approve'>" . $this->registry->getClass('output')->getReplacement("approve") . " {$this->lang->words['approve_request']}</a></li>
					<li class='negative'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=moderate&amp;pp_option=delete&amp;pp_friend_id[{$friend['member_id']}]=1&amp;md5check={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='Deny'>" . $this->registry->getClass('output')->getReplacement("deny") . " {$this->lang->words['deny_request']}</a></li>
				</ul>
				" . (($this->settings['pp_allow_member_rate']) ? ("<p class='rating'> 
						" . (($friend['pp_rating_real'] >= 1) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 2) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 3) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 4) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 5) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "
					</p>") : ("")) . "
				
				" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($friend['pp_reputation_points'] > 0) ? ("
						<p class='reputation positive'>
					") : ("")) . "
					" . (($friend['pp_reputation_points'] < 0) ? ("
						<p class='reputation negative'>
					") : ("")) . "
					" . (($friend['pp_reputation_points'] == 0) ? ("
						<p class='reputation zero'>
					") : ("")) . "
							<span class='number'>{$this->lang->words['m_reputation']} {$friend['pp_reputation_points']}</span>
						</p>") : ("")) . "						
			</li>") : ("<li id='member_id_{$friend['friends_friend_id']}' class='general_box clear member_entry " .  IPSLib::next( $this->registry->templateStriping["memberStripe"] ) . "'>
				<h3 class='bar'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($friend['member_id'],$friend['members_seo_name']) . "</h3>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><img src='{$friend['pp_thumb_photo']}' width='{$friend['pp_thumb_width']}' height='{$friend['pp_thumb_height']}' alt=\"{$friend['members_display_name']}{$this->lang->words['users_photo']}\" class='photo' /></a>	
			
				<dl class='info'>
					<dt class='clear'>{$this->lang->words['m_member_since']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->getDate($friend['joined'],"short", 0) . "</dd>
					<dt class='clear'>{$this->lang->words['m_group']}</dt>
					<dd>{$friend['_group_formatted']}</dd>
					<dt class='clear'>{$this->lang->words['m_posts']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->formatNumber( $friend['posts'] ) . "</dd>
					<dt class='clear'>{$this->lang->words['m_last_active']}</dt>
					<dd>" . $this->registry->getClass('class_localization')->getDate($friend['last_activity'],"short", 0) . "</dd>
				</dl>
				
				<ul class='user_controls clear'>
					" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $friend['friends_friend_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $friend['friends_friend_id'] )) ? ("
							<li class='mini_friend_toggle is_friend' id='friend_profile_{$friend['friends_friend_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$friend['friends_friend_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='Remove Friend'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
						") : ("
							<li class='mini_friend_toggle is_not_friend' id='friend_profile_{$friend['friends_friend_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$friend['friends_friend_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='Add as friend'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
						")) . "") : ("")) . "
					" . (($this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
						<li class='pm_button' id='pm_xxx_{$friend['friends_friend_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$friend['friends_member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_this_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
					") : ("")) . "
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$friend['friends_friend_id']}&amp;view_by_title=1&amp;search_filter_app[forums]=1", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("find_posts_link") . " {$this->lang->words['find_topics']}</a></li>
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$friend['friends_friend_id']}" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("&amp;search_filter_app[forums]=1") : ("")) . "", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("find_posts_link") . " {$this->lang->words['find_posts']}</a></li>
					" . (($friend['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
						<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;mid={$friend['friends_friend_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
					") : ("")) . "
					" . (($friend['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
						<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$friend['friends_friend_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
					") : ("")) . "
				</ul>
				" . (($this->settings['pp_allow_member_rate']) ? ("<p class='rating'> 
						" . (($friend['pp_rating_real'] >= 1) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 2) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 3) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 4) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($friend['pp_rating_real'] >= 5) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "
					</p>") : ("")) . "
				
				" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($friend['pp_reputation_points'] > 0) ? ("
						<p class='reputation positive'>
					") : ("")) . "
					" . (($friend['pp_reputation_points'] < 0) ? ("
						<p class='reputation negative'>
					") : ("")) . "
					" . (($friend['pp_reputation_points'] == 0) ? ("
						<p class='reputation zero'>
					") : ("")) . "
							<span class='number'>{$this->lang->words['m_reputation']} {$friend['pp_reputation_points']}</span>
						</p>") : ("")) . "						
			</li>")) . "
		
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- profileModern --*/
function profileModern($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null) {
$IPBHTML = "";

$this->registry->templateStriping['visitors'] = array( FALSE, "row1","row2");
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("rating", "0" ) . "
" . $this->registry->getClass('output')->addJSModule("profile", "0" ) . "
<script type='text/javascript'>
//<![CDATA[
	ipb.profile.viewingProfile = parseInt( {$member['member_id']} );
	ipb.templates['remove_friend'] = \"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=remove&amp;member_id={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'><img src='{$this->settings['img_url']}/user_delete.png' alt='{$this->lang->words['remove_friend']}' /> {$this->lang->words['remove_as_friend']}</a>\";
	ipb.templates['add_friend'] = \"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=add&amp;member_id={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'><img src='{$this->settings['img_url']}/user_add.png' alt='{$this->lang->words['add_friend']}' /> {$this->lang->words['add_friend']}</a>\";
	ipb.templates['edit_status'] = \"<span id='edit_status'><input type='text' class='input_text' style='width: 60%' id='updated_status' maxlength='150' /> <input type='submit' value='{$this->lang->words['save']}' class='input_submit' id='save_status' /> &nbsp;<a href='#' id='cancel_status' class='cancel' title='{$this->lang->words['cancel']}'>{$this->lang->words['cancel']}</a></span>\";
	
	" . (($this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $member['member_id'] )) ? ("
			ipb.profile.isFriend = true;
		") : ("
			ipb.profile.isFriend = false;
		")) . "") : ("")) . "
//]]>
</script>
<!--SKINNOTE: Added report link - feel free to change around -->
" . ((($this->memberData['member_id'] && $member['member_id'] != $this->memberData['member_id'])) ? ("
	<ul class='topic_buttons'>
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;section=reports&amp;rcom=profiles&amp;member_id={$member['member_id']}", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("user_icon") . " {$this->lang->words['report_member']}</a></li>
	</ul>
") : ("")) . "
	
" . ((($this->memberData['member_id'] && $member['member_id'] == $this->memberData['member_id']) || $this->memberData['g_is_supmod'] == 1) ? ("<!--SKINNOTE: If you are a mod and are looking at your own profile, you get two edit links - not really needed -->
	<ul class='topic_buttons'>
		" . (($this->memberData['g_is_supmod'] == 1 && $member['member_id'] != $this->memberData['member_id']) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate&amp;do=editmember&amp;auth_key={$this->member->form_hash}&amp;member={$member['member_id']}", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("user_icon") . " {$this->lang->words['supmod_edit_member']}</a></li>
		") : ("")) . "
		" . (($this->memberData['member_id'] && $member['member_id'] == $this->memberData['member_id']) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=members", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("user_edit_icon") . " {$this->lang->words['edit_profile']}</a></li>
		") : ("")) . "		
	</ul>") : ("")) . "
<div class='vcard'>
	<h2 class='maintitle'>
		<span class='left'><span class=\"fn nickname\">{$member['members_display_name']}</span>{$this->lang->words['m_profile_title']}</span>
		" . (($this->settings['pp_allow_member_rate']) ? ("<span class='rating'>
				" . (($this->memberData['member_id'] == $member['member_id'] || !$this->memberData['member_id']) ? ("{$this->lang->words['m_rating']} 
						" . (($member['pp_rating_real'] >= 1) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($member['pp_rating_real'] >= 2) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($member['pp_rating_real'] >= 3) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($member['pp_rating_real'] >= 4) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "" . (($member['pp_rating_real'] >= 5) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "<span id='rating_text' class='desc'></span>") : ("{$this->lang->words['m_rating']} 
						<a href='#' id='user_rate_1' title='{$this->lang->words['m_rate_1']}'>" . (($member['pp_rating_real'] >= 1) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "</a><a href='#' id='user_rate_2' title='{$this->lang->words['m_rate_2']}'>" . (($member['pp_rating_real'] >= 2) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "</a><a href='#' id='user_rate_3' title='{$this->lang->words['m_rate_3']}'>" . (($member['pp_rating_real'] >= 3) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "</a><a href='#' id='user_rate_4' title='{$this->lang->words['m_rate_4']}'>" . (($member['pp_rating_real'] >= 4) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "</a><a href='#' id='user_rate_5' title='{$this->lang->words['m_rate_5']}'>" . (($member['pp_rating_real'] >= 5) ? ("" . $this->registry->getClass('output')->getReplacement("rate_on") . "") : ("" . $this->registry->getClass('output')->getReplacement("rate_off") . "")) . "</a> <span id='rating_text' class='desc'></span>
					<script type='text/javascript'>
						rating = new ipb.rating( 'user_rate_', { 
											url: '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&module=ajax&section=rate&member_id={$member['member_id']}", 'public','' ), "", "" ) . "&md5check=' + ipb.vars['secure_hash'],
											cur_rating: " . ((isset($member['pp_rating_real'])) ? ("{$member['pp_rating_real']}") : ("0")) . ",
											rated: null,
											allow_rate: ( {$this->memberData['member_id']} != 0 ) ? 1 : 0,
											show_rate_text: false
										  } );
					</script>")) . "
			</span>") : ("")) . "		
	</h2>
	
	<div id='profile_overview' class='left'>
		<div class='personal_info clear general_box alt'>
			<img class=\"photo\" src='{$member['pp_main_photo']}' alt=\"{$member['members_display_name']}{$this->lang->words['users_photo']}\"  />
			" . (($member['warn_percent'] !== NULL) ? ("<div class='warn_panel clear rounded'>
					" . (($member['can_edit_warn']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=add&amp;mid={$member['member_id']}&amp;t=0&amp;st=0", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_increase']}'><img src='{$this->settings['img_url']}/warn_add.gif' alt='{$this->lang->words['add']}' class='warn_edit up' /></a><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=minus&amp;mid={$member['member_id']}&amp;t=0&amp;st=0", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_decrease']}'><img src='{$this->settings['img_url']}/warn_minus.gif' alt='{$this->lang->words['minus']}' class='warn_edit down'  /></a>
					") : ("")) . "
						<!-- SKINNOTE: Has link to open AJAX popup warn logs  -->
						<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;do=view&amp;mid={$member['member_id']}", 'public','' ), "", "" ) . "' id='warn_link_xxx_{$member['member_id']}' title='{$this->lang->words['warn_view_history']}' class='warn_link'>{$this->lang->words['warn_status']}</a></strong>
					" . (($member['warn_percent'] >= 80) ? ("
						<p class='progress_bar user_warn limit' title='{$this->lang->words['warn_level']} {$member['warn_percent']}%'>
					") : ("
						<p class='progress_bar user_warn' title='{$this->lang->words['warn_level']} {$member['warn_percent']}%'>
					")) . "
							<span style='width: {$member['warn_percent']}%'><span>{$this->lang->words['warn_level']} {$member['warn_percent']}%</span></span>
						</p>
				</div>") : ("")) . "
			<ul>
				" . (($member['spamStatus'] !== NULL && $member['member_id'] != $this->memberData['member_id']) ? ("" . (($member['spamStatus'] === TRUE) ? ("
						<li><a href='#' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, false)\">" . $this->registry->getClass('output')->getReplacement("spammer_on") . " {$this->lang->words['spm_on']}</a></li>
					") : ("
						<li><a href='{$this->settings['base_url']}&amp;app=forums&amp;module=moderate&amp;section=moderate&amp;do=setAsSpammer&amp;member_id={$member['member_id']}&amp;auth_key={$this->member->form_hash}' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, true)\">" . $this->registry->getClass('output')->getReplacement("spammer_off") . " {$this->lang->words['spm_off']}</a></li>
					")) . "") : ("")) . "
				" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("<li id='friend_toggle'>
						" . ((IPSMember::checkFriendStatus( $member['member_id'] )) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=remove&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'><img src='{$this->settings['img_url']}/user_delete.png' alt='{$this->lang->words['remove_friend']}' /> {$this->lang->words['remove_as_friend']}</a>
						") : ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=add&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'><img src='{$this->settings['img_url']}/user_add.png' alt='{$this->lang->words['add_friend']}' /> {$this->lang->words['add_me_friend']}</a>
						")) . "
					</li>") : ("")) . "
				" . ((($member['member_id'] != $this->memberData['member_id']) AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
					<li class='pm_button' id='pm_xxx_{$member['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_this_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . " {$this->lang->words['send_message']}</a></li>
				") : ("")) . "
				" . (($member['member_id'] != $this->memberData['member_id']) ? ("<!--<li id='ignore_toggle'>
						" . ((IPSMember::checkIgnoredStatus( $member['member_id'] )) ? ("
							<a href='#' title='{$this->lang->words['unignore']}'>" . $this->registry->getClass('output')->getReplacement("ignore_user") . " {$this->lang->words['unignore']}</a>
						") : ("
							<a href='#' title='{$this->lang->words['ignore']}'>" . $this->registry->getClass('output')->getReplacement("ignore_user") . " {$this->lang->words['ignore']}</a>
						")) . "
					</li>-->") : ("")) . "
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$member['member_id']}&amp;search_filter_app[forums]=1&amp;view_by_title=1", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("find_topics_link") . " {$this->lang->words['find_topics']}</a></li>
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$member['member_id']}" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("&amp;search_filter_app[forums]=1") : ("")) . "", 'public','' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("find_posts_link") . " {$this->lang->words['find_posts']}</a></li>
				" . (($this->memberData['g_mem_info'] && $this->settings['auth_allow_dnames']) ? ("
					<li id='dname_history'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=dname&amp;id={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_dname_history']}'>" . $this->registry->getClass('output')->getReplacement("display_name") . " {$this->lang->words['display_name_history']}</a></li>
				") : ("")) . "
			</ul>
		</div>
		" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($member['pp_reputation_points'] > 0) ? ("
				<div class='reputation positive'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] < 0) ? ("
				<div class='reputation negative'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] == 0) ? ("
				<div class='reputation zero'>
			") : ("")) . "
					<span class='number'>{$this->lang->words['m_reputation']} {$member['pp_reputation_points']}</span>
					" . (($member['author_reputation'] && $member['author_reputation']['text']) ? ("
						<span class='title'>{$member['author_reputation']['text']}</span>
					") : ("")) . "
					" . (($member['author_reputation'] && $member['author_reputation']['image']) ? ("
						<span class='image'><img src='{$member['author_reputation']['image']}' alt='{$this->lang->words['m_reputation']}' /></span>
					") : ("")) . "
				</div>") : ("")) . "
		<div class='info'>
			<dl>
				<dt>{$this->lang->words['m_group']}</dt>
				<dd>{$member['g_title']}</dd>
				<dt>{$this->lang->words['m_posts']}</dt>
				<dd " . ((!$this->settings['disable_profile_stats']) ? ("title='{$member['_total_pct']}% {$this->lang->words['total_percent']}'") : ("")) . ">" . $this->registry->getClass('class_localization')->formatNumber( $member['posts'] ) . "" . ((!$this->settings['disable_profile_stats']) ? (" ({$member['_posts_day']} {$this->lang->words['posts_per_day']})") : ("")) . "</dd>
				" . ((!$this->settings['disable_profile_stats'] AND $member['favorite_id']) ? ("
					<dt>{$this->lang->words['m_active_in']}</dt>
					<dd title='{$member['_fav_percent']}% {$this->lang->words['fav_percent']}'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$member['favorite_id']}", 'public','' ), "{$this->registry->class_forums->forum_by_id[ $member['favorite_id'] ]['name_seo']}", "showforum" ) . "'>{$this->registry->class_forums->forum_by_id[ $member['favorite_id'] ]['name']}</a> ({$member['_fav_posts']} {$this->lang->words['fav_posts']})
					</dd>
				") : ("")) . "
				<dt>{$this->lang->words['m_member_since']}</dt>
				<dd>" . $this->registry->getClass('class_localization')->getDate($member['joined'],"joined", 0) . "</dd>
				<dt>{$this->lang->words['m_profile_views']}</dt>
				<dd>" . $this->registry->getClass('class_localization')->formatNumber( $member['members_profile_views'] ) . "</dd>
				<dt>{$this->lang->words['m_last_active']}</dt>
				<dd>" . (($member['_online']) ? ("" . $this->registry->getClass('output')->getReplacement("user_online") . "") : ("" . $this->registry->getClass('output')->getReplacement("user_offline") . "")) . " {$member['_last_active']}</dd>
				<dt>{$this->lang->words['m_currently']}</dt>
				<dd>" . (($member['_online']) ? ("
						{$member['online_extra']}
					") : ("
						{$this->lang->words['online_offline']}
					")) . "
				</dd>
			</dl>
		</div>
		
		" . (($member['custom_fields']) ? ("
			".$this->__f__4deb8619bfd18efab8fb544053a37913($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."		") : ("")) . "
		
		" . (($member['pp_setting_count_visitors']) ? ("<div class='general_box alt' id='latest_visitors'>
				<h3 class='bar'>{$this->lang->words['latest_visitors']}</h3>
				" . ((is_array( $visitors ) && count( $visitors )) ? ("
										<ul>
						".$this->__f__3df8a44529406be52a05390b4d6e1b1f($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."					</ul>
				") : ("
					<p class='no_messages'>{$this->lang->words['no_latest_visitors']}</p>
				")) . "
			</div>") : ("")) . "
	</div>
	<div id='main_profile_body' class='right'>
		<div class='message user_status in_profile' id='status_box'>
			" . $this->registry->getClass('output')->getReplacement("user_status") . "&nbsp;&nbsp; <span class='user'><strong>{$member['members_display_name']}</strong></span> <span class='status' id='status_holder'>" . (($member['pp_status']) ? ("{$member['pp_status']}") : ("<em>{$this->lang->words['not_set_status']}</em>")) . "</span>
			
			" . (($member['member_id'] == $this->memberData['member_id'] AND ! $this->memberData['gbw_no_status_update']) ? ("
				<form id='update_status_form' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status' method='post'>
					<fieldset>
					<input type='hidden' name='k' value='{$this->member->form_hash}' />
						{$this->lang->words['update_to']} <input type='text' class='text' name='new_status' /> <input type='submit' value='{$this->lang->words['update']}' />
					</fieldset>
				</form>
			") : ("")) . "
		</div>
		<br />
		
		<div class='recent_activity'>
			<ol class='tab_bar no_title mini'>
				".$this->__f__11da9e8a532f3c51a215d0bb4cdaba06($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."			</ol>
			<div id='tab_content' class='row1 profile_pane'>
				<div id='tab_{$default_tab}'>
					{$default_tab_content}
				</div>
			</div>
		</div>
		<script type='text/javascript'>
			ipb.profile.activeTab = '$default_tab';
		</script>
	
		<div class='about_contact'>
			<div class='about_info left general_box row2'>
				<h3 class='bar'>{$this->lang->words['my_info']}</h3>
				<dl>
					" . (($member['title'] != '') ? ("
						<dt>{$this->lang->words['m_member_title']}</dt>
						<dd>{$member['title']}</dd>
					") : ("")) . "
					<dt>{$this->lang->words['m_age_prefix']}</dt>
					" . (($member['_age'] > 0) ? ("
						<dd>{$member['_age']} {$this->lang->words['m_years_old']}</dd>
					") : ("
						<dd>{$this->lang->words['m_age_unknown']}</dd>
					")) . "
					<dt>{$this->lang->words['m_birthday_prefix']}</dt>
					" . (($member['bday_day']) ? ("<!-- SKINNOTE: We should use the localized date formatting for this -->
						<dd>{$member['_bday_month']} {$member['bday_day']}" . (($member['bday_year']) ? (", {$member['bday_year']}") : ("")) . "</dd>") : ("
						<dd>{$this->lang->words['m_bday_unknown']}</dd>
					")) . "
					" . (($member['custom_fields']['profile_info'] != "") ? ("
						".$this->__f__6dc75556bd3870b5038b6b8c16d94b4d($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."					") : ("")) . "
				</dl>
			</div>
	
			<div class='contact_info right general_box row2'>
				<h3 class='bar'>{$this->lang->words['contact_info']}</h3>
				<dl>
					
					<dt>{$this->lang->words['m_email']}</dt>
					<dd class='clearfix'>
						" . (($this->memberData['g_access_cp'] == 1) ? ("
							<a href='mailto:{$member['email']}'>{$member['email']}</a>
						") : ("" . ((!$member['hide_email']) ? ("
								<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=contact&amp;do=Mail&amp;MID={$member['member_id']}", 'public','' ), "", "" ) . "'>{$this->lang->words['click_to_email']}</a>
							") : ("
								<em>{$this->lang->words['private']}</em>
							")) . "")) . "						
					</dd>	
					" . ((is_array( $member['custom_fields']['contact'])) ? ("
						".$this->__f__2e87633dd0e4cd852396744278609d94($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."					") : ("")) . "
				</dl>
			</div>
		</div>
	" . (($this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends'] AND $member['pp_setting_count_friends']) ? ("<div class='friend_list clear' id='friend_list'>
			<h3 class='bar'>{$this->lang->words['m_title_friends']}</h3>
			" . ((is_array($friends) and count($friends)) ? ("<ul class='clearfix'>
				".$this->__f__993ef088f456ab4187ab53142611315f($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields)."				</ul>
				" . (($member['_total_approved_friends'] > $member['_total_displayed_friends']) ? ("<p class='clear'>
					<em>{$this->lang->words['showing_50_rand_friends']} {$member['_total_approved_friends']}</em>
					" . (($member['_total_approved_friends'] > 50) ? ("
						&nbsp;(<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=view&amp;member_id={$member['member_id']}", 'public','' ), "", "" ) . "' id='view-all-friends'>{$this->lang->words['friends_view_all']}</a></strong>)
					") : ("")) . "
				</p>") : ("")) . "") : ("
				<p>
					<em>{$member['members_display_name']} {$this->lang->words['no_friends_yet']}</em>
				</p>
			")) . "
		</div>") : ("")) . "
	
		" . (($member['pp_setting_count_comments'] > 0) ? ("<div class='comments' id='comment_wrap'>
				<h3 class='bar'>{$this->lang->words['m_title_comments']}</h3>
				" . (($this->memberData['member_id']) ? ("
					<form id='commentForm' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=comments&amp;do=add_new_comment' method='post'>
						<fieldset>
							<input type='hidden' name='member_id' value='{$member['member_id']}' />
							<div id='post_comment' class='clear row2'>
								<img src='{$this->memberData['pp_mini_photo']}' width='{$this->memberData['pp_mini_width']}' height='{$this->memberData['pp_mini_height']}' alt='{$this->lang->words['your_photo']}' class='photo left clear' />
								<textarea class='input_textarea' cols='50' rows='3' id='comment_text' name='comment_text'></textarea>
								<br />
								<input type='submit' class='clear input_submit' value='{$this->lang->words['comment_submit_post']}' id='comment_submit' />
								<span class='desc' id='char_remain_wrap' style='display: none'>{$this->lang->words['chars_remaining']} <span id='char_remain'>400</span></span>
								<script type='text/javascript'>
									$('char_remain_wrap').show();
									ipb.vars['max_comment_length'] = 400;
								</script>
							</div> 
						</fieldset>
					</form>
					<br />
				") : ("")) . "
				" . (($comments) ? ("
					$comments
				") : ("
					<p>
						<em>{$member['members_display_name']} {$this->lang->words['no_profile_comments']}</em>
					</p>
				")) . "
			</div>") : ("")) . "
	</div>
</div>
" . $this->registry->getClass('output')->getTemplate('global')->include_highlighter() . "";
return $IPBHTML;
}


function __f__fc4296db689b13527f037d171528d16d($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null,$group='',$mdata='')
{
	$_ips___x_retval = '';
	foreach( $member['custom_fields'][ $group ] as $key => $value )
	{
		
		$_ips___x_retval .= "
										{$value}
									
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__4deb8619bfd18efab8fb544053a37913($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $member['custom_fields'] as $group => $mdata )
	{
		
		$_ips___x_retval .= "
				" . (($group != 'profile_info' AND $group != 'contact') ? ("" . ((is_array( $member['custom_fields'][ $group ] ) AND count( $member['custom_fields'][ $group ] )) ? ("
						<div class='other_contact clearfix'>
							<div class='general_box clearfix row2' id='custom_fields_{$group}'>
								<h3 class='bar'>{$member['custom_field_groups'][ $group ]}</h3>
								<dl>
									".$this->__f__fc4296db689b13527f037d171528d16d($tabs,$member,$comments,$friends,$visitors,$default_tab,$default_tab_content,$fields,$group,$mdata)."								</dl>
							</div>
						</div>
					") : ("")) . "") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__3df8a44529406be52a05390b4d6e1b1f($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $visitors as $friend )
	{
		
		$_ips___x_retval .= "
						<li class='" .  IPSLib::next( $this->registry->templateStriping["visitors"] ) . "'>
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' ><img src='{$friend['pp_mini_photo']}' width='{$friend['pp_mini_width']}' height='{$friend['pp_mini_height']}' alt='{$this->lang->words['photo']}' class='photo' /></a><span class='name'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name_short']}</a></span>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($friend['member_id'], $friend['members_seo_name']) . "<br />
							<span class='desc'>{$friend['_visited_date']}</span>
						</li>				
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__11da9e8a532f3c51a215d0bb4cdaba06($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $tabs as $tab )
	{
		
		$_ips___x_retval .= "
					<li id='tab_link_{$tab['plugin_key']}' class='tab_toggle " . (($tab['plugin_key'] == $default_tab) ? ("active") : ("")) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab={$tab['plugin_key']}", 'public','' ), "{$member['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view']} {$tab['_lang']}'>{$tab['_lang']}</a></li>
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__6dc75556bd3870b5038b6b8c16d94b4d($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $member['custom_fields']['profile_info'] as $key => $value )
	{
		
		$_ips___x_retval .= "
							{$value}
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__2e87633dd0e4cd852396744278609d94($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $member['custom_fields']['contact'] as $field )
	{
		
		$_ips___x_retval .= "
							{$field}
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__993ef088f456ab4187ab53142611315f($tabs=array(), $member=array(), $comments="", $friends=array(), $visitors=array(), $default_tab='posts', $default_tab_content='', $fields=null)
{
	$_ips___x_retval = '';
	foreach( $friends as $friend )
	{
		
		$_ips___x_retval .= "
					<li>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' ><img src='{$friend['pp_thumb_photo']}' width='{$friend['pp_thumb_width']}' height='{$friend['pp_thumb_height']}' alt='{$this->lang->words['photo']}' class='photo' /></a><br />
						<span class='name'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", 'public','' ), "{$friend['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$friend['members_display_name_short']}</a> " . $this->registry->getClass('output')->getTemplate('global')->user_popup($friend['member_id'], $friend['members_seo_name']) . "</span>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- showCard --*/
function showCard($member, $download=0) {
$IPBHTML = "";
$IPBHTML .= "<div class='vcard userpopup'>
	<h3><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", 'public','' ), "{$member['members_seo_name']}", "showuser" ) . "\" class=\"fn nickname url\">{$member['members_display_name']}</a></h3>
	<div>
		" . (($member['pp_status']) ? ("
			<p class='message user_status'>" . $this->registry->getClass('output')->getReplacement("user_status") . "&nbsp; <strong>{$member['members_display_name']}</strong> {$member['pp_status']}</p>
		") : ("")) . "
		<div class='info'>
			<img class='photo' src=\"{$member['pp_thumb_photo']}\" alt=\"{$this->lang->words['get_photo']}\" width='{$member['pp_thumb_width']}' height='{$member['pp_thumb_height']}' alt='photo' />
			<dl>
				<dt>{$this->lang->words['m_group']}</dt>
				<dd>{$member['g_title']}</dd>
				<dt>{$this->lang->words['m_posts']}</dt>
				<dd title='{$member['_posts_day']} {$this->lang->words['posts_per_day']}'>" . $this->registry->getClass('class_localization')->formatNumber( $member['posts'] ) . "</dd>
				<dt>{$this->lang->words['m_member_since']}</dt>
				<dd>" . $this->registry->getClass('class_localization')->getDate($member['joined'],"joined", 0) . "</dd>
				<dt>{$this->lang->words['m_last_active']}</dt>
				<dd>" . (($member['_online']) ? ("" . $this->registry->getClass('output')->getReplacement("user_online") . "") : ("" . $this->registry->getClass('output')->getReplacement("user_offline") . "")) . " {$member['_last_active']}</dd>
				<dt>{$this->lang->words['m_currently']}</dt>
				<dd>" . (($member['_online']) ? ("
						{$member['online_extra']}
					") : ("
						{$this->lang->words['online_offline']}
					")) . "
				</dd>
				" . (($this->memberData['g_access_cp'] == 1) ? ("
					<dt>{$this->lang->words['m_email']}</dt>
					<dd><a href='mailto:{$member['email']}'>{$member['email']}</a></dd>
				") : ("")) . "
			</dl>
		</div>
		
		<ul class='user_controls clear'>
			" . (($member['spamStatus'] !== NULL && $member['member_id'] != $this->memberData['member_id']) ? ("" . (($member['spamStatus'] === TRUE) ? ("
					<li><a href='#' title='{$this->lang->words['spm_on']}' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, false)\">" . $this->registry->getClass('output')->getReplacement("spammer_on") . "</a></li>
				") : ("
					<li><a title='{$this->lang->words['spm_off']}' href='{$this->settings['base_url']}&amp;app=forums&amp;module=moderate&amp;section=moderate&amp;do=setAsSpammer&amp;member_id={$member['member_id']}&amp;auth_key={$this->member->form_hash}' onclick=\"return ipb.global.toggleFlagSpammer({$member['member_id']}, true)\">" . $this->registry->getClass('output')->getReplacement("spammer_off") . "</a></li>
				")) . "") : ("")) . "
			" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("" . ((IPSMember::checkFriendStatus( $member['member_id'] )) ? ("
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
				") : ("
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$member['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>								
				")) . "") : ("")) . "
			" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $member['member_id'] AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
				<li class='pm_button' id='pm_xxx_{$member['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_this_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
			") : ("")) . "
			
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$member['member_id']}&amp;search_filter_app[forums]=1&amp;view_by_title=1", 'public','' ), "", "" ) . "' title='{$this->lang->words['find_topics']}'>" . $this->registry->getClass('output')->getReplacement("find_topics_link") . "</a></li>		
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_posts&amp;mid={$member['member_id']}" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("&amp;search_filter_app[forums]=1") : ("")) . "", 'public','' ), "", "" ) . "' title='{$this->lang->words['find_posts']}'>" . $this->registry->getClass('output')->getReplacement("find_posts_link") . "</a></li>
			" . (($member['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;mid={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
			") : ("")) . "
			" . (($member['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$member['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
			") : ("")) . "
		</ul>
		
		
		" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("" . (($member['pp_reputation_points'] > 0) ? ("
				<div class='reputation positive'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] < 0) ? ("
				<div class='reputation negative'>
			") : ("")) . "
			" . (($member['pp_reputation_points'] == 0) ? ("
				<div class='reputation zero'>
			") : ("")) . "
					<span class='number'>{$this->lang->words['m_reputation']} {$member['pp_reputation_points']}</span>
				</div>") : ("")) . "
	</div>
</div>";
return $IPBHTML;
}

/* -- showComments --*/
function showComments($member, $comments=array(), $new_id=0, $return_msg='', $links='') {
$IPBHTML = "";

$this->registry->templateStriping['comments'] = array( FALSE, "row1","off");
$IPBHTML .= "" . ((is_array($comments) and count($comments)) ? ("<div id='comment_innerwrap' class='comment_wrap clearfix'>
		<div class='topic_controls" . ((!$this->memberData['member_id']) ? (" no-form") : ("")) . "'>
			{$links}
		</div>
		<ol id='comment_list' class='clear'>
				".$this->__f__0e550966fdf7bd2a052a69f34a06c64d($member,$comments,$new_id,$return_msg,$links)."		</ol>
		<div class='topic_controls'>
			{$links}
		</div>
	</div>
	" . (($new_id != 0) ? ("
		<div class='topic_controls'>
			{$links}
		</div>
	") : ("")) . "") : ("")) . "";
return $IPBHTML;
}


function __f__0e550966fdf7bd2a052a69f34a06c64d($member, $comments=array(), $new_id=0, $return_msg='', $links='')
{
	$_ips___x_retval = '';
	foreach( $comments as $comment )
	{
		
		$_ips___x_retval .= "
			" . (($new_id == 0 || $comment['comment_id'] == $new_id) ? ("<li id='comment_id_{$comment['comment_id']}'>
					<div class='comment clearfix " .  IPSLib::next( $this->registry->templateStriping["comments"] ) . " " . ((!$comment['comment_approved']) ? (" moderated") : ("")) . "'>
						<img src='{$comment['pp_thumb_photo']}' width='{$comment['pp_thumb_width']}' height='{$comment['pp_thumb_height']}' class='photo' alt='{$this->lang->words['photo']}' />
						<h4>
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$comment['member_id']}", 'public','' ), "{$comment['members_seo_name']}", "showuser" ) . "\">{$comment['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($comment['member_id'],$comment['members_seo_name']) . "
						</h4>
						<span class='posted_date desc'>
							{$comment['_comment_date']}
						</span>
						<div id='comment_{$comment['comment_id']}' class='comment_content'>
							{$comment['comment_content']}
						</div>
						" . (($this->memberData['member_id'] == $member['member_id'] OR $this->memberData['g_is_supmod']) ? ("<ul class='comment_options'>
								<li>
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=comments&amp;do=delete&amp;comment_id={$comment['comment_id']}&amp;member_id={$member['member_id']}&amp;authKey={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['delete_this_comment']}' class='delete_comment'>{$this->lang->words['delete_comment_text']}</a>
								</li>
								" . ((! $comment['comment_approved']) ? ("
									<li>
										<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=comments&amp;do=approve&amp;comment_id={$comment['comment_id']}&amp;member_id={$member['member_id']}&amp;authKey={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['approve_this_comment']}'>{$this->lang->words['m_approve']}</a>
									</li>
								") : ("")) . "									
							</ul>") : ("")) . "
					</div>
				</li>") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- showIframeComments --*/
function showIframeComments($member, $comments, $pages) {
$IPBHTML = "";
$IPBHTML .= "<div id='pp-iframe-wrap' class='pp-contentbox-back' style='overflow:auto'>
<form onsubmit='check_form()' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=comments&amp;module=profile&amp;do=save&amp;member_id={$member['member_id']}&amp;md5check={$this->member->form_hash}", 'public','' ), "", "" ) . "' method='POST'>
	" . ((is_array($comments) and count($comments)) ? ("".$this->__f__47587dc2923c7207a14858a96a2a2ddd($member,$comments,$pages)."		<div class='pp-contentbox-entry-noheight'>
			<div style='float:right'>
				" . ((( $member['member_id'] == $this->memberData['member_id'] ) OR ( $this->memberData['g_is_supmod'] )) ? ("
					<select name='pp-moderation' id='pp-moderation'>
						<option value='approve'>{$this->lang->words['m_comment_app']}</option>
						<option value='unapprove'>{$this->lang->words['m_comment_unapp']}</option>
						<option value='delete'>{$this->lang->words['m_comment_delete']}</option>
					</select>
					<input type='submit' class='button' value='{$this->lang->words['m_go_button']}' />
				") : ("")) . "
			</div>
			<div style='margin-top:7px'>{$pages}&nbsp;</div>") : ("
		<div class='post1' style='padding:6px'>
			<em>{$this->lang->words['m_no_comments']} {$member['members_display_name']}.</em>
		</div>
	")) . "
</form>
</div>
<br /><br /><br /> <!-- Gotta give room for page jump... -->
<script type='text/javascript'>
//<![CDATA
var _saved = parseInt( \"{$this->request['_saved']}\" );
if ( _saved )
{
	parent.ips_personal_portal.reload_comments();
}
// Check form
function check_form()
{
	var selectbox = document.getElementById('pp-moderation');
	var chosen    = selectbox.options[ selectbox.selectedIndex ].value;
	
	if ( chosen == 'delete' )
	{
		if ( confirm(\"{$this->lang->words['m_confirm']}\") )
		{
			return true;
		}
		else
		{
			return false;
		}
	}
	else
	{
		return true;
	}
}
//]]>
</script>";
return $IPBHTML;
}


function __f__47587dc2923c7207a14858a96a2a2ddd($member, $comments, $pages)
{
	$_ips___x_retval = '';
	foreach( $comments as $comment )
	{
		
		$_ips___x_retval .= "
			" . (($comment['comment_approved']) ? ("
				<div class='pp-contentbox-entry-noheight' id='pp-comment-entry-main-{$comment['comment_id']}'>
			") : ("
				<div class='pp-contentbox-entry-noheight-mod' id='pp-comment-entry-main-{$comment['comment_id']}'>
			")) . "
				<div class='pp-tiny-text'>
				<div class='pp-image-thumb-wrap-floatright'><img src='{$comment['pp_thumb_photo']}' width='{$comment['pp_thumb_width']}' height='{$comment['pp_thumb_height']}' alt='' /></div>
					" . ((( $member['member_id'] == $this->memberData['member_id'] ) OR ( $this->memberData['g_is_supmod'] )) ? ("
						<!-- MOD CHECKBOX -->
						<input type='checkbox' class='input-checkbox' id=\"pp-checked-{$comment['comment_id']}\" name=\"pp-checked[{$comment['comment_id']}]\" value='1' onclick=\"parent.ips_personal_portal.toggle_comment_box('{$comment['comment_id']}', 1)\" />
						<!-- / MOD CHECKBOX -->
					") : ("")) . "
					{$comment['_pp_gender_image']} <strong>" . (($comment['member_id']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$comment['member_id']}", 'public','' ), "{$comment['members_seo_name']}", "showuser" ) . "' target='_parent'>") : ("")) . "{$comment['members_display_name']}" . (($comment['member_id']) ? ("</a>") : ("")) . "</strong>
					<br />
					{$comment['comment_content']}
					<br />
					<strong>{$comment['_comment_date']}</strong>
				</div>
			</div>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- showPhoto --*/
function showPhoto($member) {
$IPBHTML = "";
$IPBHTML .= "<div id=\"photowrap\">
	<div id=\"phototitle\">{$member['members_display_name']}</div>
	<div id=\"photoimg\"><img src=\"{$member['pp_main_photo']}\" alt=\"{$this->lang->words['get_photo']}\" width='{$member['pp_main_width']}' height='{$member['pp_main_height']}' /></div>
</div>";
return $IPBHTML;
}

/* -- tabAboutMe --*/
function tabAboutMe($member=array()) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar'>{$this->lang->words['pp_tab_aboutme']}</h3>
<div class='general_box'>
	" . (($member['pp_about_me'] OR $member['signature']) ? ("{$member['pp_about_me']}
		
		" . (($member['signature']) ? ("
				{$member['signature']}
		") : ("")) . "") : ("
		{$this->lang->words['err_no_aboutme_to_show']}
	")) . "
</div>";
return $IPBHTML;
}

/* -- tabNoContent --*/
function tabNoContent($langkey) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar'>{$this->lang->words['tab_message_h']}</h3>
<div class='general_box'>
	{$this->lang->words[ $langkey ]}
</div>";
return $IPBHTML;
}

/* -- tabPosts --*/
function tabPosts($content) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar'>{$this->lang->words['posts_made']}</h3>
<div class='general_box alt'>
	<ol>
		$content
	</ol>
</div>";
return $IPBHTML;
}

/* -- tabSingleColumn --*/
function tabSingleColumn($row=array(), $read_more_link='', $url='', $title='') {
$IPBHTML = "";
$IPBHTML .= "<li style='list-style:none'>
	" . (($title) ? ("" . (($url) ? ("
			<h4><a href=\"$url\" title=\"View topic\">$title</a></h4>
		") : ("
			<h4>$title</h4>
		")) . "") : ("")) . "
	<p class='posted_info'>{$this->lang->words['posted']} {$row['_date_array']['mday']} {$row['_date_array']['smonth']} {$row['_date_array']['year']}</p>
	<div class='post_body'>
		{$row['post']}
	</div>
</li>";
return $IPBHTML;
}

/* -- tabTopics --*/
function tabTopics($content) {
$IPBHTML = "";
$IPBHTML .= "<h3 class='bar'>{$this->lang->words['topics_started']}</h3>
<div class='general_box alt'>
	<ol>
		$content
	</ol>
</div>";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>