<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:03 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_printpage_1 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- choose_form --*/
function choose_form($fid="",$tid="",$title="") {
$IPBHTML = "";

$this->registry->templateStriping['strip'] = array( FALSE, "row1","row2");
$IPBHTML .= "<h2>{$this->lang->words['tvo_title']}&nbsp;{$title}</h2>
<p class='message unspecific'>{$this->lang->words['please_choose']}</p>
<div class='generic_bar'></div><div class='post_form'>
	<ul>
		<li class='field'>
			<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=printtopic&amp;client=printer&amp;f={$fid}&amp;t={$tid}", 'public','' ), "", "" ) . "\">{$this->lang->words['o_print_title']}</a></strong><br />{$this->lang->words['o_print_desc']}
		</li>
		<li class='field'>
			<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=printtopic&amp;client=html&amp;f={$fid}&amp;t={$tid}", 'public','' ), "", "" ) . "\">{$this->lang->words['o_html_title']}</a></strong><br />{$this->lang->words['o_html_desc']}
		</li>
		<li class='field'>
			<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=printtopic&amp;client=wordr&amp;f={$fid}&amp;t={$tid}", 'public','' ), "", "" ) . "\">{$this->lang->words['o_word_title']}</a></strong><br />{$this->lang->words['o_word_desc']}
		</li>
	</ul>
	<p class='submit'>
		<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$tid}", 'public','' ), "", "" ) . "\" title='{$this->lang->words['back_topic']}'>&laquo; {$this->lang->words['back_topic']}</a>
	</p>
</div>";
return $IPBHTML;
}

/* -- pp_end --*/
function pp_end() {
$IPBHTML = "";
$IPBHTML .= "<!--Copyright-->
" . (($this->settings['ipb_copy_number'] == '') ? ("
<p id='copyright'>{$this->lang->words['powered_by']}Invision Power Board (http://www.)<br />&copy; Invision Power Services (http://www.)</p>
") : ("")) . "
	</div>
</body>
</html>";
return $IPBHTML;
}

/* -- pp_header --*/
function pp_header($forum_name="",$topic_title="",$topic_starter="",$fid="",$tid="",$IPS_DOC_CHAR_SET=IPS_DOC_CHAR_SET) {
$IPBHTML = "";
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
<html xml:lang=\"en\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">
	<head>
		<meta http-equiv=\"content-type\" content=\"text/html; charset={$IPS_DOC_CHAR_SET}\" />
		<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_print.css\" />
		<title>{$this->settings['board_name']}</title>
	</head>
	<body id='ipboard_body'>
	<div id=\"content\">
		<h2>{$topic_title} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$tid}", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['click_toview']}\">{$this->lang->words['view_original']}</a></h2>
		<div id='breadcrumb'>{$this->settings['board_name']} -> {$forum_name} -> {$topic_title}</div>
		<br /><br />";
return $IPBHTML;
}

/* -- pp_postentry --*/
function pp_postentry($poster="",$entry="") {
$IPBHTML = "";
$IPBHTML .= "<div class='post_block first hentry " . (($post['post']['queued']==1) ? ("moderated") : ("")) . "' id='post_id_{$post['post']['pid']}'>
	<div class='post_wrap'>
		<h3>{$entry['members_display_name']}</h3>
		<p class='posted_info'>
			" . (($post['post']['icon_id']) ? ("
				<img src=\"{$this->settings['public_dir']}style_extra/post_icons/icon{$post['post']['icon_id']}.gif\" alt=\"{$this->lang->words['icon']}\" />&nbsp;
			") : ("")) . "
			{$this->lang->words['posted_prefix']} {$entry['post_date']}
		</p>
		<div class='post_body'>
			<div class='post entry-content'>
				{$entry['post']}
				<!--IBF.ATTACHMENT_{$entry['pid']}-->
				<br />
			</div>
		</div>
	</div>	
</div>";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>