<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Sat, 19 Sep 2009 18:22:13 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_1 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- defaultHeader --*/
function defaultHeader() {
$IPBHTML = "";
$IPBHTML .= "<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "false", "" ) . "' title='{$this->lang->words['go_home']}' rel=\"home\" accesskey='1'><img src='" . $this->registry->getClass('output')->getReplacement("logo_img") . "' alt='{$this->lang->words['logo']}' /></a>";
return $IPBHTML;
}

/* -- forum_jump --*/
function forum_jump($html) {
$IPBHTML = "";
$IPBHTML .= "<form id='forum_jump' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "' method='post'>
		<fieldset>
			<select name='showforum' class='input_select'>
				<optgroup label=\"{$this->lang->words['forum_jump']}\">
					<option value='0'>{$this->lang->words['forum_home']}</option>
					{$html}
				</optgroup>
			</select>
			" . (($this->member->session_type != 'cookie') ? ("<input type='hidden' name='s' value='{$this->member->session_id}' />") : ("")) . "
			<input type='submit' value='{$this->lang->words['jmp_go']}' class='input_submit alt' />
		</fieldset>
	</form>";
return $IPBHTML;
}

/* -- globalTemplate --*/
function globalTemplate($html, $documentHeadItems, $css, $jsModules, $metaTags, $header_items=array(), $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";

$this->templateVars['forumActive'] = "";
$this->__default__templateVars['forumActive'] = "";
if ( IPS_APP_COMPONENT == 'forums' )
{
	$this->templateVars['forumActive'] = "active";
}
else {$this->templateVars['forumActive'] = $this->__default__templateVars['forumActive']; }

$this->templateVars['membersActive'] = "";
$this->__default__templateVars['membersActive'] = "";
if ( IPS_APP_COMPONENT == 'members' )
{
	$this->templateVars['membersActive'] = "active";
}
else {$this->templateVars['membersActive'] = $this->__default__templateVars['membersActive']; }

$this->templateVars['helpActive'] = "";
$this->__default__templateVars['helpActive'] = "";
if ( IPS_APP_COMPONENT == 'core' AND $this->request['module'] == 'help' )
{
	$this->templateVars['helpActive'] = "active";
}
else {$this->templateVars['helpActive'] = $this->__default__templateVars['helpActive']; }

$this->did_first = 0;
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
	<html xml:lang=\"en\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\"" . ((IPSLib::fbc_enabled() === TRUE) ? (" xmlns:fb=\"http://www.facebook.com/2008/fbml\"") : ("")) . ">
	<head>
		<meta http-equiv=\"content-type\" content=\"text/html; charset={$this->settings['gb_char_set']}\" />
		<title>{$header_items['title']}" . (($header_items['page']) ? (" {$this->lang->words['page_title_page']} {$header_items['page']}") : ("")) . "</title>
		<link rel=\"shortcut icon\" href='" . (($this->registry->output->isHTTPS) ? ("{$this->settings['board_url_https']}") : ("{$this->settings['board_url']}")) . "/favicon.ico' />
		<script type='text/javascript'>
			jsDebug = " . intval($this->settings['_jsDebug']) . "; /* Must come before JS includes */
			USE_RTE = " . (($this->memberData['members_editor_choice'] == 'rte' && $this->memberData['_canUseRTE'] === TRUE) ? ("1") : ("0")) . ";
			inACP   = false;
		</script>
		" . $this->registry->getClass('output')->getTemplate('global')->includeCSS($css) . "
		<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />-->
		" . $this->registry->getClass('output')->getTemplate('global')->includeMeta($metaTags) . "" . $this->registry->getClass('output')->getTemplate('global')->includeJS($jsModules) . "" . $this->registry->getClass('output')->getTemplate('global')->includeFeeds($documentHeadItems) . "" . $this->registry->getClass('output')->getTemplate('global')->includeRTL() . "		
		" . $this->registry->getClass('output')->getTemplate('global')->includeVars() . "
		<script type='text/javascript'>
			Loader.boot();
		</script>
	</head>
	<body id='ipboard_body'>
		<div id='ipbwrapper'>
			<h1>{$this->settings['board_name']}: {$header_items['title']}</h1>
			<p id='content_jump'><a id='top'></a><a href='#j_content' title='{$this->lang->words['jump_to_content']}' accesskey='m'>{$this->lang->words['jump_to_content']}</a></p>
		
			" . ((($this->memberData['g_is_supmod'] == 1 OR ( isset( $this->memberData['access_report_center'] ) AND $this->memberData['access_report_center'] ) )) ? ("<div id='admin_bar'>
					" . (($this->memberData['g_access_cp'] == 1 AND $this->settings['security_remove_acp_link'] == 0) ? ("
					<p class='right'>
						<a href=\"{$this->settings['_admin_link']}\" title='{$this->lang->words['admin_cp']}'>{$this->lang->words['login_to_acp']} &gt;</a>
					</p>
					") : ("")) . "
					<strong>{$this->lang->words['mod_tools']}</strong> 
					<ul id='mod_tools'>
						" . (($this->memberData['g_is_supmod'] == 1) ? ("
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=members&amp;area=mod_ipaddress", 'public','' ), "", "" ) . "' title='{$this->lang->words['ip_lookup']}'>{$this->lang->words['ip_lookup']}</a></li>
							<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=forums&amp;area=modAddAnnouncement&amp;do=add", 'public','' ), "", "" ) . "' title='{$this->lang->words['post_announcement']}'>{$this->lang->words['post_announcement']}</a></li>
						") : ("")) . "
						" . (($this->memberData['access_report_center']) ? ("<li " . (($this->memberData['_cache']['report_num'] > 0) ? ("class='active'") : ("")) . "><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;do=index", 'public','' ), "", "" ) . "\" title='{$this->lang->words['view_reports']}'>{$this->memberData['_cache']['report_num']} {$this->lang->words['report_member_bar']}</a></li>") : ("")) . "
					</ul>
				</div>") : ("")) . "
			<div id='header'>
				<div id='branding'>
					" . ((method_exists( $this->registry->output->getTemplate( $this->registry->getCurrentApplication() . '_global' ), 'overwriteHeader' )) ? ("
						" . $this->registry->getClass('output')->getTemplate(''.$this->registry->getCurrentApplication().'_global')->overwriteHeader() . "
					") : ("
						" . $this->registry->getClass('output')->getTemplate('global')->defaultHeader() . "
					")) . "
				</div>
						
				" . (($this->memberData['member_id']) ? ("<div id='user_navigation' class='logged_in'>
						<img src='{$this->memberData['pp_thumb_photo']}' alt=\"{$this->memberData['members_display_name']}{$this->lang->words['users_photo']}\" width='{$this->memberData['pp_thumb_width']}' height='{$this->memberData['pp_thumb_height']}' class='photo' />
						<div id='user_info'>
							<p>
								<span class='hide'>{$this->lang->words['logged_in_as']} </span>
Logged in as
								<a id='user_link' class='ipbmenu' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$this->memberData['member_id']}", 'public','' ), "{$this->memberData['members_seo_name']}", "showuser" ) . "\"  title='{$this->lang->words['your_profile']}'>{$this->memberData['members_display_name']} <img src='{$this->settings['img_url']}/opts_arrow.png' alt='&gt;' /></a>" . (($this->memberData['msg_count_new'] != 0) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging", 'public','' ), "", "" ) . "' id='new_msg_count' title='{$this->memberData['msg_count_new']} {$this->lang->words['msg_new']}'>{$this->memberData['msg_count_new']}<span class='hide'> {$this->lang->words['msg_new']}</span></a>") : ("")) . "
							</p>
							<ul id='user_link_menucontent'>
							
							
								
							<ul id='user_other'>
								<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=logout&amp;k={$this->member->form_hash}", 'public','' ), "", "" ) . "\">{$this->lang->words['log_out']}</a></li>
								
								" . (($this->memberData['member_group_id'] == $this->settings['auth_group']) ? ("
									<li><strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=register&amp;do=reval", 'public','' ), "", "" ) . "\" title='{$this->lang->words['resend_val']}'>{$this->lang->words['resend_val']}</a></strong></li>
								") : ("")) . "
							</ul>
							<script type='text/javascript'>
								if( $('user_link_menucontent') ){
									$('user_link_menucontent').hide();
								}
							</script>
							" . $this->registry->getClass('output')->addJSModule("friends", "0" ) . "
						</div>
					</div>") : ("
					<div id='user_navigation' class='not_logged_in'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", 'public','' ), "", "" ) . "' title='{$this->lang->words['sign_in']}'>" . $this->registry->getClass('output')->getReplacement("signin_icon") . " {$this->lang->words['sign_in']}</a>
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=register", 'public','' ), "", "" ) . "\" title='{$this->lang->words['register']}'>" . $this->registry->getClass('output')->getReplacement("register_icon") . " {$this->lang->words['register']}</a>
						<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help", 'public','' ), "", "" ) . "\" title='{$this->lang->words['view_help']}' rel=\"help\" accesskey='6'>" . $this->registry->getClass('output')->getReplacement("help_icon") . " {$this->lang->words['sj_help']}</a>
					</div>
				
				")) . "
			
				<div id='primary_nav'>
					<div id='search'>
						" . ((! in_array( $this->settings['search_method'], array( 'traditional', 'sphinx' ) )) ? ("
						<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=quick_search&amp;search_filter_app[all]=1", 'public','' ), "", "" ) . "\" method=\"post\" id='search-box' >
						") : ("<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=quick_search&amp;search_filter_app[" . ((! empty($this->request['search_app'])) ? ("{$this->request['search_app']}") : ("" . ((IPSSearchIndex::appIsSearchable( $this->registry->getCurrentApplication() )) ? ("{$this->registry->getCurrentApplication()}") : ("forums")) . "")) . "]=1", 'public','' ), "", "" ) . "\" method=\"post\" id='search-box' >")) . "
							<fieldset>
							
								<label for='main_search' class='hide'>{$this->lang->words['sj_search']}</label>
								<input type='text' id='main_search' name='search_term' class='text_input' size='17' tabindex='6' />
								<input type='submit' class='submit_input' value='{$this->lang->words['sj_search']}' />
								<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search", 'public','' ), "", "" ) . "' title='{$this->lang->words['advanced_search']}' accesskey='4' rel=\"search\" id='adv_search'>{$this->lang->words['advanced']}</a>
							</fieldset>
						</form>
					</div>
					<ul>
					" . (($this->settings['home_url']) ? ("
							<li id='nav_home' class='left'><a href='{$this->settings['home_url']}' title='{$this->lang->words['homepage_title']}' rel=\"home\">{$this->settings['home_name']}</a></li>
						") : ("")) . " 
																							
						" . ((is_array($header_items['applications']) AND count($header_items['applications'])) ? ("
							".$this->__f__f3ef81aefc61e1ddbb3a00ce02d56217($html,$documentHeadItems,$css,$jsModules,$metaTags,$header_items,$items,$footer_items,$stats)."						") : ("")) . "
					</ul>
				</div>
				" . ((is_array( $items['pmData'] )) ? ("<div id='pm_notification'>
						<div id='pm_wrap'>
							<img src='{$items['pmData']['authorData']['pp_thumb_photo']}' alt=\"{$items['pmData']['authorData']['members_display_name']}{$this->lang->words['users_photo']}\" width='{$items['pmData']['authorData']['pp_thumb_width']}' height='{$items['pmData']['authorData']['pp_thumb_height']}' class='photo' />
							<h2>{$items['pmData']['authorData']['members_display_name']} " . (($items['pmData']['_type'] == 'new') ? ("{$this->lang->words['sent_new_convo']}") : ("{$this->lang->words['replied_convo']}")) . "</h2>
							<p>
								<strong>{$this->lang->words['pc_subject']}</strong> {$items['pmData']['mt_title']}<br />
								<strong>{$this->lang->words['pc_replies']}</strong> " . intval( $items['pmData']['mt_replies'] ) . "<br />
								<strong>{$this->lang->words['pc_sent']}</strong> " . $this->registry->getClass('class_localization')->getDate($items['pmData']['msg_date'],"short", 0) . "
							</p>
							<p class='excerpt'>
								" . IPSText::truncate( $items['pmData']['msg_post'], 500 ) . "
							</p>
							<br />
							<ul class='topic_buttons ok_thanks'>
								<li><a href='#j_content' id='close_pm_notification'><img src='{$this->settings['img_url']}/cross.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['ignore_conversation']}</a></li>
								<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=view&amp;do=findMessage&amp;topicID={$items['pmData']['mt_id']}&amp;msgID=__firstUnread__", 'public','' ), "", "" ) . "'><img src='{$this->settings['img_url']}/email.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['global_pm_read']}</a></li>
							</ul>
						</div>
					</div>
					<script type='text/javascript'>
						$('pm_notification').hide();
					</script>") : ("")) . "
			
			<!-- NAVIGATION TOP LEFT	<div id='secondary_nav'>
					<ul id='breadcrumb' class='left'>
												" . ((!$this->settings['remove_forums_nav'] OR ipsRegistry::$current_application == 'forums') ? ("<li class='first'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "act=idx", 'public','' ), "false", "" ) . "'>{$this->settings['board_name']}</a></li>
							" . (($this->did_first=1) ? ("") : ("")) . "") : ("")) . " 
						".$this->__f__ce9338f8ac36f63d75adce3df1cb47a3($html,$documentHeadItems,$css,$jsModules,$metaTags,$header_items,$items,$footer_items,$stats)."					</ul>
					<ul id='section_links' class='right'>
						" . (($this->settings['gl_show'] and $this->settings['gl_title']) ? ("<li><a href='" . (($this->settings['gl_link']) ? ("{$this->settings['gl_link']}") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=boardrules", 'public','' ), "", "" ) . "")) . "'>" . (($this->settings['gl_title']) ? ("{$this->settings['gl_title']}") : ("{$this->lang->words['board_rules']}")) . "</a></li>") : ("")) . "
						<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=new_posts&amp;search_filter_app[" . (($this->registry->getCurrentApplication() != 'core' AND IPSSearchIndex::appIsSearchable( $this->registry->getCurrentApplication() )) ? ("{$this->registry->getCurrentApplication()}") : ("forums")) . "]=1", 'public','' ), "", "" ) . "' accesskey='2'>{$this->lang->words['view_new_posts']}</a></li>
						<li><img src='{$this->settings['img_url']}/feed.png' alt='{$this->lang->words['rss_feed']}' id='rss_feed' class='clickable' /></li> 
					</ul>
				</div>
			</div>  -->
			<div id='content' class='clear'>
				<a id='j_content'></a>
				" . (($html) ? ("{$html}") : ("")) . "
				<br class='clear' />
			</div>
			<div id='footer_utilities' class='clearfix clear rounded'>
				<h2 class='hide'>{$this->lang->words['skin_and_lang']}</h2>
				" . (($this->settings['allow_skins'] AND $footer_items['skin_chooser']) ? ("" . (($this->memberData['userAgentLocked'] AND ! $this->memberData['userAgentBypass']) ? ("
						<p id='useragent_msg'>
							{$this->lang->words['skin_browser_set']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_formatted']}&amp;unlockUserAgent=1", 'public','' ), "", "" ) . "'>{$this->lang->words['override_browser_theme']}</a>
						</p>
					") : ("
						<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_formatted']}", 'public','' ), "", "" ) . "\" method=\"post\" class='left'>
							<fieldset>
								<input type='hidden' name='k' value='{$this->member->form_hash}' />
								<label for='newSkin' class='hide'>{$this->lang->words['theme_prefix']}</label>
								<select name=\"settingNewSkin\" id='newSkin'>
									{$footer_items['skin_chooser']}
								</select>
								<input type='submit' value='{$this->lang->words['jmp_go']}' class='input_submit alt' id='newSkinSubmit' />
							</fieldset>
						</form>
					")) . "") : ("")) . "
				<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_formatted']}", 'public','' ), "", "" ) . "\" method=\"post\" class='left'>
					<fieldset>
						<input type='hidden' name='k' value='{$this->member->form_hash}' />
						<input type='hidden' name='setlanguage' value='1' />
						<input type=\"hidden\" name=\"langurlbits\" value=\"{$this->settings['query_string_safe']}&amp;cal_id={$this->request['cal_id']}\" />
						<label for='newLang' class='hide'>{$this->lang->words['language_prefix']}</label>
						<select name=\"langid\" id='newLang'>
								{$footer_items['lang_chooser']}
						</select>
						<input type='submit' class='input_submit alt' value='{$this->lang->words['jmp_go']}' id='newLangSubmit' />
					</fieldset>
				</form>
				<h2 class='hide'>{$this->lang->words['exec_stats']}</h2>
				<ul class='right'>
					<li>{$this->lang->words['time_now']} {$footer_items['time']}
						" . (($this->memberData['member_id'] AND $this->memberData['last_visit']) ? ("<p>{$this->lang->words['you_last_visit']} " . $this->registry->getClass('class_localization')->getDate($this->memberData['last_visit'],"short", 0) . "</p>") : ("")) . "
					</li>
					" . (($this->memberData['member_id'] and $this->settings['debug_level']) ? ("<li><img src='{$this->settings['img_url']}/stats_time.png' alt='{$this->lang->words['icon']}' /> {$stats['ex_time']} {$this->lang->words['stats_sec']}</li>
						<li><img src='{$this->settings['img_url']}/stats_server.png' alt='{$this->lang->words['icon']}' /> {$stats['server_load']}</li>
						<li><img src='{$this->settings['img_url']}/stats_database.png' alt='{$this->lang->words['icon']}' /> {$stats['queries']} " . ((IPS_SQL_DEBUG_MODE) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_safe']}&amp;debug=1", 'public','' ), "", "" ) . "'>") : ("")) . "{$this->lang->words['stats_queries']}" . ((IPS_SQL_DEBUG_MODE) ? ("</a>") : ("")) . "</li>
						<li><img src='{$this->settings['img_url']}/stats_compression.png' alt='{$this->lang->words['icon']}' /> {$stats['gzip_status']}</li>") : ("")) . "
				</ul>
			</div>
			<!-- __FOOTER__ -->
			<!-- /__FOOTER__ -->
			<!--DEBUG_STATS-->
			<div id='board_footer'>
				<ul id='utility_links' class='left'>
					<li><a href='#top' title='{$this->lang->words['go_to_top']}'>{$this->lang->words['back_to_top']}</a></li>
					<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "' title='{$this->lang->words['sj_home']}'>Home</a></li>
					<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=deleteCookies&amp;k={$this->member->form_hash}", 'public','' ), "", "" ) . "\" title='{$this->lang->words['delete_all_cookies_title']}'>{$this->lang->words['delete_my_cookies']}</a></li>
				</ul>
				{$footer_items['copyright']}
			</div>
			{$stats['task']}
			" . (($this->settings['do_include_lightbox_real']) ? ("" . $this->registry->getClass('output')->getTemplate('global')->include_lightbox_real() . "") : ("")) . "
		</div>
	</body>
</html>";
return $IPBHTML;
}


function __f__f3ef81aefc61e1ddbb3a00ce02d56217($html, $documentHeadItems, $css, $jsModules, $metaTags, $header_items=array(), $items=array(), $footer_items=array(), $stats=array())
{
	$_ips___x_retval = '';
	foreach( $header_items['applications'] as $data )
	{
		
$this->templateVars['appActive'] = "";
$this->__default__templateVars['appActive'] = "";
if ( $data['app_active'] )
{
	$this->templateVars['appActive'] = "active";
}
else {$this->templateVars['appActive'] = $this->__default__templateVars['appActive']; }

		$_ips___x_retval .= "
								" . (($data['app_show']) ? ("
																		<li id='nav_app_{$data['app_dir']}' class=\"left " . $this->templateVars["appActive"] . "\"><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app={$data['app_dir']}", 'public','' ), "false", "" ) . "' title='{$this->lang->words['go_to_prefix']}" . IPSLib::getAppTitle( $data['app_dir'] ) . "'>" . IPSLib::getAppTitle( $data['app_dir'] ) . "</a></li>
								") : ("")) . "
							
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__ce9338f8ac36f63d75adce3df1cb47a3($html, $documentHeadItems, $css, $jsModules, $metaTags, $header_items=array(), $items=array(), $footer_items=array(), $stats=array())
{
	$_ips___x_retval = '';
	foreach( $items['navigation'] as $idx => $data )
	{
		
		$_ips___x_retval .= "
							<li" . ((!$this->did_first) ? (" class='first'") : ("")) . ">" . (($this->did_first) ? ("<span class='nav_sep'>&gt;</span>") : ("")) . " " . (($data[1]) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data[1]}", 'public','' ), "$data[2]", "$data[3]" ) . "' title='{$this->lang->words['nav_return_to']}{$data[0]}'>") : ("")) . "{$data[0]}" . (($data[1]) ? ("</a>") : ("")) . "</li>
							" . (($this->did_first=1) ? ("") : ("")) . "
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- include_highlighter --*/
function include_highlighter($load_when_needed=0) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addToDocumentHead( 'importcss', "{$this->settings['public_dir']}style_css/prettify.css" ) . "
	<script type=\"text/javascript\" src=\"{$this->settings['public_dir']}js/3rd_party/prettify/prettify.js\"></script>
	<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/prettify/lang-sql.js'></script>
	<!-- By default we load generic code, php, css, sql and xml/html; load others here if desired -->
	<script type=\"text/javascript\">
	//<![CDATA[
		Event.observe( window, 'load', function(e){ prettyPrint() });
	//]]>
	</script>";
return $IPBHTML;
}

/* -- include_lightbox --*/
function include_lightbox() {
$IPBHTML = "";

$this->settings['do_include_lightbox_real']	= 1;
$IPBHTML .= "";
return $IPBHTML;
}

/* -- include_lightbox_real --*/
function include_lightbox_real() {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/lightbox.js'></script>
<script type='text/javascript'>
//<![CDATA[
	// Lightbox Configuration
	LightboxOptions = Object.extend({
	    fileLoadingImage:        '{$this->settings['img_url']}/lightbox/loading.gif',     
	    fileBottomNavCloseImage: '{$this->settings['img_url']}/lightbox/closelabel.gif',
	    overlayOpacity: 0.8,   // controls transparency of shadow overlay
	    animate: true,         // toggles resizing animations
	    resizeSpeed: 7,        // controls the speed of the image resizing animations (1=slowest and 10=fastest)
	    borderSize: 10,         //if you adjust the padding in the CSS, you will need to update this variable
		// When grouping images this is used to write: Image # of #.
		// Change it for non-english localization
		labelImage: \"{$this->lang->words['lightbox_label']}\",
		labelOf: \"{$this->lang->words['lightbox_of']}\"
	}, window.LightboxOptions || {});
//]]>
</script>";
return $IPBHTML;
}

/* -- includeCSS --*/
function includeCSS($css) {
$IPBHTML = "";

$this->minify = array();
$IPBHTML .= "" . ((is_array( $css['import'] )) ? ("" . (($this->settings['use_minify']) ? ("") : ("")) . "
	".$this->__f__7068ed6a2d1745c36a3bed2ad2c555ee($css)."	" . (($this->settings['use_minify'] AND count($this->minify)) ? ("
		<link rel=\"stylesheet\" type=\"text/css\" media='screen' href=\"{$this->settings['public_dir']}min/index.php?f=" . str_replace( $this->settings['public_dir'], 'public/', implode( ',', $this->minify ) ) . "\" />
	") : ("")) . "") : ("")) . "
" . ((is_array( $css['inline'] ) AND count( $css['inline'] )) ? ("
	".$this->__f__fda26393f47573904184910cb3ab4c5d($css)."") : ("")) . "
<!--[if lte IE 7]>
	<link rel=\"stylesheet\" type=\"text/css\" title='Main' media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_ie.css\" />
<![endif]-->";
return $IPBHTML;
}


function __f__7068ed6a2d1745c36a3bed2ad2c555ee($css)
{
	$_ips___x_retval = '';
	foreach( $css['import'] as $data )
	{
		
if( $this->settings['use_minify'] AND ( ! $data['attributes'] OR stripos( $data['attributes'], 'screen' ) !== false ) )
			{
				$this->minify[] = "{$data['content']}";
			}

		$_ips___x_retval .= "
				" . ((!$this->settings['use_minify'] OR ( $data['attributes'] AND stripos( $data['attributes'], 'screen' ) === false )) ? ("
			<link rel=\"stylesheet\" type=\"text/css\" {$data['attributes']} href=\"{$data['content']}\" />
		") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__fda26393f47573904184910cb3ab4c5d($css)
{
	$_ips___x_retval = '';
	foreach( $css['inline'] as $data )
	{
		
		$_ips___x_retval .= "
	<style type=\"text/css\" {$data['attributes']}>
		/* Inline CSS */
		{$data['content']}
	</style>
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- includeFeeds --*/
function includeFeeds($documentHeadItems) {
$IPBHTML = "";
$IPBHTML .= "" . ((count($documentHeadItems)) ? ("
	".$this->__f__ca5232d8882d36785753ada658e47b51($documentHeadItems)."") : ("")) . "";
return $IPBHTML;
}


function __f__81c2eafd38ca713d08666a4de79b106c($documentHeadItems,$type='',$idx='')
{
	$_ips___x_retval = '';
	foreach( $documentHeadItems[ $type ] as $idx => $data )
	{
		
		$_ips___x_retval .= "
			" . (($type == 'javascript') ? ("
				<script type=\"text/javascript\" src=\"{$data}\" charset=\"<% CHARSET %>\"></script>
			") : ("")) . "
			" . (($type == 'rss') ? ("
				<link rel=\"alternate feed\" type=\"application/rss+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
			") : ("")) . "
			" . (($type == 'rsd') ? ("
				<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
			") : ("")) . "
			" . (($type == 'raw') ? ("
				{$data}
			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__ca5232d8882d36785753ada658e47b51($documentHeadItems)
{
	$_ips___x_retval = '';
	foreach( $documentHeadItems as $type => $idx )
	{
		
		$_ips___x_retval .= "
		".$this->__f__81c2eafd38ca713d08666a4de79b106c($documentHeadItems,$type,$idx)."	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- includeJS --*/
function includeJS($jsModules) {
$IPBHTML = "";
$IPBHTML .= "" . (($this->settings['use_minify']) ? ("" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/prototype/1.6/prototype.js'></script>
		<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/scriptaculous/1.8/scriptaculous.js?load=effects,dragdrop,builder'></script>") : ("
		<script type='text/javascript' src='{$this->settings['public_dir']}min/index.php?g=js'></script>
	")) . "
	<script type='text/javascript' src='{$this->settings['public_dir']}min/index.php?charset={$this->settings['gb_char_set']}&amp;f=public/js/ipb.js,public/js/ips.quickpm.js" . ((count($jsModules)) ? (",public/js/ips." . implode('.js,public/js/ips.', array_unique( array_keys( $jsModules ) ) ) . ".js") : ("")) . ",cache/lang_cache/{$this->lang->lang_id}/ipb.lang.js' charset='{$this->settings['gb_char_set']}'></script>") : ("" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/prototype/1.6/prototype.js'></script>") : ("
		<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/prototype.js'></script>
	")) . "
	<script type='text/javascript' src='{$this->settings['public_dir']}js/ipb.js?load=quickpm," . implode(',', array_unique( array_keys( $jsModules ) ) ) . "'></script>
	" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/scriptaculous/1.8/scriptaculous.js?load=effects,dragdrop,builder'></script>") : ("
		<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/scriptaculous/scriptaculous-cache.js'></script>
	")) . "
	<script type=\"text/javascript\" src='{$this->settings['cache_dir']}lang_cache/{$this->lang->lang_id}/ipb.lang.js' charset='{$this->settings['gb_char_set']}'></script>")) . "";
return $IPBHTML;
}

/* -- includeMeta --*/
function includeMeta($metaTags) {
$IPBHTML = "";
$IPBHTML .= "" . ((is_array( $metaTags ) AND count( $metaTags )) ? ("
	".$this->__f__796a55e2e894881a53b8bc812caf55b7($metaTags)."") : ("")) . "";
return $IPBHTML;
}


function __f__796a55e2e894881a53b8bc812caf55b7($metaTags)
{
	$_ips___x_retval = '';
	foreach( $metaTags as $tag => $content )
	{
		
		$_ips___x_retval .= "
	<meta name=\"$tag\" content=\"$content\" />
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- includeRTL --*/
function includeRTL() {
$IPBHTML = "";

$this->isRtlLang	= false;
$IPBHTML .= "".$this->__f__7888810a70b01655c13270d1cedcb5ea()."<script type='text/javascript'>
	var isRTL	= false;
	var rtlIe	= '';
	var rtlFull	= '';
</script>
" . (($this->isRtlLang AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl.css' )) ? ("
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\" />
	<script type='text/javascript'>
		var rtlFull	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl.css\";
		var isRTL	= true;
	</script>
") : ("" . (($this->isRtlLang AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl.css' )) ? ("
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl.css\" />
		<script type='text/javascript'>
			var rtlFull	= \"{$this->settings['public_dir']}style_css/ipb_rtl.css\";
			var isRTL	= true;
		</script>
	") : ("")) . "")) . "
" . (($this->isRtlLang AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/' . $this->registry->output->skin['_csscacheid'] . '/ipb_rtl_ie.css' )) ? ("
	<!--[if lte IE 7]>
	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\" />
	<![endif]-->
	<script type='text/javascript'>
		var rtlIe	= \"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_rtl_ie.css\";
	</script>
") : ("" . (($this->isRtlLang AND file_exists( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_css/ipb_rtl_ie.css' )) ? ("
		<!--[if lte IE 7]>
		<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\" />
		<![endif]-->
		<script type='text/javascript'>
			var rtlIe	= \"{$this->settings['public_dir']}style_css/ipb_rtl_ie.css\";
		</script>
	") : ("")) . "")) . "";
return $IPBHTML;
}


function __f__7888810a70b01655c13270d1cedcb5ea()
{
	$_ips___x_retval = '';
	foreach( $this->cache->getCache('lang_data') as $data )
	{
		
		$_ips___x_retval .= "
	" . ((intval($this->member->language_id) == intval($data['lang_id'])) ? ("" . (($data['lang_isrtl']) ? ("" . (($this->isRtlLang = true) ? ("") : ("")) . "") : ("")) . "") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- includeVars --*/
function includeVars() {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript'>
	//<![CDATA[
		/* ---- URLs ---- */
		ipb.vars['base_url'] 			= '" . (($this->registry->output->isHTTPS) ? ("" . str_replace( 'http://', 'https://', "" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "" ) . "") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", 'public','' ), "", "" ) . "")) . "';
		ipb.vars['board_url']			= '{$this->settings['board_url']}';
		ipb.vars['loading_img'] 		= '{$this->settings['img_url']}/loading.gif';
		ipb.vars['active_app']			= '{$this->registry->getCurrentApplication()}';
		ipb.vars['upload_url']			= '{$this->settings['upload_url']}';
		/* ---- Member ---- */
		ipb.vars['member_id']			= parseInt( {$this->memberData['member_id']} ),
		ipb.vars['is_supmod']			= parseInt( " . intval($this->memberData['g_is_supmod']) . " ),
		ipb.vars['is_admin']			= parseInt( {$this->memberData['g_access_cp']} ),
		ipb.vars['secure_hash'] 		= '{$this->member->form_hash}';
		ipb.vars['session_id']			= '{$this->member->session_id}';
		ipb.vars['can_befriend']		= " . (($this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("true") : ("false")) . ";
		/* ---- cookies ----- */
		ipb.vars['cookie_id'] 			= '{$this->settings['cookie_id']}';
		ipb.vars['cookie_domain'] 		= '{$this->settings['cookie_domain']}';
		ipb.vars['cookie_path']			= '{$this->settings['cookie_path']}';
		/* ---- Rate imgs ---- */
		ipb.vars['rate_img_on']			= '{$this->settings['img_url']}/bullet_star.png';
		ipb.vars['rate_img_off']		= '{$this->settings['img_url']}/bullet_star_off.png';
		ipb.vars['rate_img_rated']		= '{$this->settings['img_url']}/bullet_star_rated.png';
		/* ---- Uploads ---- */
		ipb.vars['swfupload_swf']		= '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "js/3rd_party/swfupload/swfupload.swf", 'public_dir','' ), "", "" ) . "';
		ipb.vars['swfupload_enabled']	= " . (($this->settings['uploadFormType']) ? ("true") : ("false")) . ";
		ipb.vars['use_swf_upload']		= ( '{$this->memberData['member_uploader']}' == 'flash' ) ? true : false;
		ipb.vars['swfupload_debug']		= false; /* SKINNOTE: Turn off for production */
		/* ---- other ---- */
		ipb.vars['use_live_search'] 	= 0;
		ipb.vars['live_search_limit'] 	= 4;
		ipb.vars['highlight_color']		= \"#ade57a\";
		ipb.vars['charset']				= \"{$this->settings['gb_char_set']}\";
		ipb.vars['use_rte']				= 1;
		ipb.vars['image_resize']		= " . (($this->settings['resize_linked_img']) ? ("{$this->settings['resize_img_percent']}") : ("0")) . ";
		ipb.vars['seo_enabled']			= " . intval($this->settings['use_friendly_urls']) . ";
		" . (($this->settings['use_friendly_urls']) ? ("
		ipb.vars['seo_params']			= " . json_encode($this->registry->getClass('output')->seoTemplates['__data__']) . ";
		") : ("")) . "
		/* Templates/Language */
		ipb.templates['ajax_loading'] 	= \"<div id='ajax_loading'>\" + ipb.lang['loading'] + \"</div>\";
		ipb.templates['close_popup']	= \"<img src='{$this->settings['img_url']}/close_popup.png' alt='x' />\";
		ipb.templates['rss_shell']		= new Template(\"<ul id='rss_menu'>#{items}</ul>\");
		ipb.templates['rss_item']		= new Template(\"<li><a href='#{url}' title='#{title}'>#{title}</a></li>\");
		ipb.templates['resized_img']	= new Template(\"<span>{$this->lang->words['resized_image']}</span>\");
		ipb.templates['m_add_friend']	= new Template(\"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id=#{id}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a>\");
		ipb.templates['m_rem_friend']	= new Template(\"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id=#{id}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a>\");
		ipb.templates['autocomplete_wrap'] = new Template(\"<ul id='#{id}' class='ipb_autocomplete' style='width: 250px;'></ul>\");
		ipb.templates['autocomplete_item'] = new Template(\"<li id='#{id}'><img src='#{img}' alt='' width='#{img_w}' height='#{img_h}' />&nbsp;&nbsp;#{itemvalue}</li>\");
		ipb.templates['page_jump']		= new Template(\"<div id='#{id}_wrap' class='ipbmenu_content'><h3 class='bar'>{$this->lang->words['global_page_jump']}</h3><input type='text' class='input_text' id='#{id}_input' size='8' /> <input type='submit' value='{$this->lang->words['jmp_go']}' class='input_submit add_folder' id='#{id}_submit' /></div>\");
	//]]>
	</script>";
return $IPBHTML;
}

/* -- paginationTemplate --*/
function paginationTemplate($work, $data) {
$IPBHTML = "";
$IPBHTML .= "" . (($work['pages'] > 1) ? ("<ul class='pagination left'>
		<li class='total'>({$work['pages']} {$this->lang->words['tpl_pages']})</li>
		<li class='pagejump clickable pj{$data['uniqid']}'>
			" . $this->registry->getClass('output')->getReplacement("dropdown") . "
			<script type='text/javascript'>
				ipb.global.registerPageJump( '{$data['uniqid']}', { url: \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "" . (($data['isFriendly']) ? ("/") : ("")) . "\", stKey: '{$data['startValueKey']}', perPage: {$data['itemsPerPage']}, totalPages: {$work['pages']} } );
			</script>
		</li>
		" . ((1 < ($work['current_page'] - $data['dotsSkip'])) ? ("
			<li class='first'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=0", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "' title='{$this->lang->words['tpl_gotofirst']}' rel='start'>&laquo; {$this->lang->words['ps_first']}</a></li>
		") : ("")) . "
		" . (($work['current_page'] > 1) ? ("
			<li class='prev'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] - $data['itemsPerPage'] ) . "", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_prev']}\" rel='prev'>&larr;</a></li>
		") : ("")) . "
		" . ((is_array( $work['_pageNumbers'] ) && count( $work['_pageNumbers'] )) ? ("
			".$this->__f__94033653ffecedb70239bc496fd332ee($work,$data)."		") : ("")) . "
		" . (($work['current_page'] < $work['pages']) ? ("
			<li class='next'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=" . intval( $data['currentStartValue'] + $data['itemsPerPage'] ) . "", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_next']}\" rel='next'>&rarr;</a></li>
		") : ("")) . "
		" . ((isset( $work['_showEndDots'] ) && $work['_showEndDots']) ? ("
			<li class='last'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}=" . intval( ( $work['pages'] - 1 ) * $data['itemsPerPage'] ) . "", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"{$this->lang->words['tpl_gotolast']}\" rel='last'>{$this->lang->words['ps_last']} &raquo;</a></li>
		") : ("")) . "
	</ul>") : ("
	<span class='pagination no_pages left'>{$this->lang->words['page_1_of_1']}</span>
")) . "";
return $IPBHTML;
}


function __f__94033653ffecedb70239bc496fd332ee($work, $data)
{
	$_ips___x_retval = '';
	foreach( $work['_pageNumbers'] as $_real => $_page )
	{
		
		$_ips___x_retval .= "
				" . (($_real == $data['currentStartValue']) ? ("
					<li class='active'>{$_page}</li>
				") : ("
					<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$data['baseUrl']}&amp;{$data['startValueKey']}={$_real}", 'public','' ), "{$data['seoTitle']}", "{$data['seoTemplate']}" ) . "\" title=\"$_page\">{$_page}</a></li>
				")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- signature_separator --*/
function signature_separator($sig="") {
$IPBHTML = "";
$IPBHTML .= "<div class=\"signature\">
	{$sig}
</div>";
return $IPBHTML;
}

/* -- user_popup --*/
function user_popup($memberid=0, $seoName='') {
$IPBHTML = "";
$IPBHTML .= "" . (($memberid AND $this->memberData['g_mem_info']) ? (" <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser=$memberid", 'public','' ), "{$seoName}", "showuser" ) . "' class='__user __id{$memberid}' title='{$this->lang->words['view_profile']}'>" . $this->registry->getClass('output')->getReplacement("user_popup") . "</a>") : ("")) . "";
return $IPBHTML;
}

/* -- userInfoPane --*/
function userInfoPane($author, $contentid, $options) {
$IPBHTML = "";
$IPBHTML .= "<ul class='user_details'>
		" . (($author['member_id'] AND $author['avatar']) ? ("
			<li class='avatar'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$author['member_id']}", 'public','' ), "{$author['members_seo_name']}", "showuser" ) . "\" title=\"{$this->lang->words['view_profile']}\">{$author['avatar']}</a></li>
		") : ("
			<li class='avatar'>{$author['avatar']}</li>
		")) . "
		" . (($author['title']) ? ("
			<li class='title'>{$author['title']}</li>
		") : ("")) . "
		" . (($author['member_rank_img']) ? ("<li class='group_icon'>
			" . (($author['member_rank_img_i'] == 'img') ? ("
				<img src='{$author['member_rank_img']}' alt='{$this->lang->words['icon']}' />
			") : ("
				{$author['member_rank_img']}
			")) . "
			</li>") : ("")) . "
	</ul>
	<div style='margin: 0 auto;'>
		<ul class='user_controls clear'>
			" . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $author['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends'] && $author['member_id']) ? ("" . ((IPSMember::checkFriendStatus( $author['member_id'] )) ? ("
					<li class='mini_friend_toggle is_friend' id='friend_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id={$author['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a></li>
				") : ("
					<li class='mini_friend_toggle is_not_friend' id='friend_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id={$author['member_id']}&amp;secure_key={$this->member->form_hash}", 'public','' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a></li>
				")) . "") : ("")) . "
			" . (($this->memberData['g_use_pm'] AND $this->memberData['member_id'] != $author['member_id'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) && $author['member_id']) ? ("
				<li class='pm_button' id='pm_{$contentid}_{$author['member_id']}'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$author['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['pm_member']}'>" . $this->registry->getClass('output')->getReplacement("send_msg") . "</a></li>
			") : ("")) . "
			" . (($author['has_blog'] AND IPSLib::appIsInstalled( 'blog' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;mid={$author['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_blog']}'>" . $this->registry->getClass('output')->getReplacement("blog_link") . "</a></li>
			") : ("")) . "
			" . (($author['has_gallery'] AND IPSLib::appIsInstalled( 'gallery' )) ? ("
				<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=user&amp;section=user&amp;user={$author['member_id']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['view_gallery']}'>" . $this->registry->getClass('output')->getReplacement("gallery_link") . "</a></li>
			") : ("")) . "
		</ul>
	</div>
	<ul class='user_fields'>
		<li>
			<span class='ft'>{$this->lang->words['m_group']}</span>
			<span class='fc'>{$author['_group_formatted']}</span>
		</li>
		" . (($author['member_id']) ? ("
			<li>
				<span class='ft'>{$this->lang->words['m_posts']}</span>
				<span class='fc'>" . $this->registry->getClass('class_localization')->formatNumber( intval( $author['posts'] ) ) . "</span>
			</li>
			<li>
				<span class='ft'>{$this->lang->words['m_joined']}</span>
				<span class='fc'>" . $this->registry->getClass('class_localization')->getDate($author['joined'],"joined", 0) . "</span>
			</li>
		") : ("")) . "
		" . (($author['custom_fields'] != "") ? ("
			".$this->__f__16b99107a5d1351d0d29b3851421e3eb($author,$contentid,$options)."		") : ("")) . "
	</ul>
	" . (($author['warn_percent'] !== NULL) ? ("<br class='clear' />
		<div class='warn_panel clear rounded'>
			" . (($this->settings['warn_show_rating']) ? ("<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;do=view&amp;mid={$author['member_id']}", 'public','' ), "", "" ) . "' id='warn_link_{$contentid}_{$author['member_id']}' title='{$this->lang->words['warn_view_history']}' class='warn_link'>{$this->lang->words['warn_status']}</a></strong>
				<p class='rating_mode user_warn' title='{$this->lang->words['warn_level']} {$author['warn_percent']}%'>
					" . (($author['can_edit_warn']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=minus&amp;mid={$author['member_id']}&amp;t=0&amp;st=0", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_decrease']}'><img src='{$this->settings['img_url']}/warn_minus.gif' alt='{$this->lang->words['minus']}' class='warn_edit down'  /></a>
					") : ("")) . "
					&lt;&nbsp;{$this->settings['warn_min']} ( {$author['warn_level']} ) {$this->settings['warn_max']}&nbsp;&gt;
					" . (($author['can_edit_warn']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=add&amp;mid={$author['member_id']}&amp;t={$this->request['t']}&amp;st={$this->request['st']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_increase']}'><img src='{$this->settings['img_url']}/warn_add.gif' alt='{$this->lang->words['add']}' class='warn_edit up' /></a>
					") : ("")) . "
				</p>") : ("" . (($author['can_edit_warn']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=add&amp;mid={$author['member_id']}&amp;t={$this->request['t']}&amp;st={$this->request['st']}", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_increase']}'><img src='{$this->settings['img_url']}/warn_add.gif' alt='{$this->lang->words['add']}' class='warn_edit up' /></a><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;type=minus&amp;mid={$author['member_id']}&amp;t=0&amp;st=0", 'public','' ), "", "" ) . "' title='{$this->lang->words['warn_decrease']}'><img src='{$this->settings['img_url']}/warn_minus.gif' alt='{$this->lang->words['minus']}' class='warn_edit down'  /></a>
				") : ("")) . "
					<strong><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=warn&amp;section=warn&amp;do=view&amp;mid={$author['member_id']}", 'public','' ), "", "" ) . "' id='warn_link_{$contentid}_{$author['member_id']}' title='{$this->lang->words['warn_view_history']}' class='warn_link'>{$this->lang->words['warn_status']}</a></strong>
				" . (($author['warn_percent'] >= 80) ? ("
					<p class='progress_bar user_warn limit' title='{$this->lang->words['warn_level']} {$author['warn_percent']}%'>
				") : ("
					<p class='progress_bar user_warn' title='{$this->lang->words['warn_level']} {$author['warn_percent']}%'>
				")) . "
					<span style='width: {$author['warn_percent']}%'><span>{$this->lang->words['warn_level']} {$author['warn_percent']}%</span></span>
				</p>")) . "
		</div>") : ("")) . "";
return $IPBHTML;
}


function __f__5032ca801b271e6ef1b22937d7207233($author, $contentid, $options,$group='',$data='')
{
	$_ips___x_retval = '';
	foreach( $author['custom_fields'][ $group ] as $field )
	{
		
		$_ips___x_retval .= "
					" . (($field != '') ? ("
						<li>
							{$field}
						</li>
					") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__16b99107a5d1351d0d29b3851421e3eb($author, $contentid, $options)
{
	$_ips___x_retval = '';
	foreach( $author['custom_fields'] as $group => $data )
	{
		
		$_ips___x_retval .= "
				".$this->__f__5032ca801b271e6ef1b22937d7207233($author,$contentid,$options,$group,$data)."			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>