<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:25 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_3 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- birthday --*/
function birthday($user, $pyear) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
$IPBHTML .= "<h2 class='hide'>{$this->lang->words['board_index_title']}</h2>
<div id='board_index' class='clearfix'>
	<div id='categories' class='no_sidebar clearfix'>
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__a36796a478eb074de2f1aba2739e8f1e($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
</div>";
return $IPBHTML;
}


function __f__2134e8580b542710da3e81047cc9d4f7($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$_ips___x_retval .= "
											<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", 'public','' ), "{$__data[2]}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$__data[1]}</a></li>
										
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__d01f2b4019ec1ea149cdd8437e8d4c28($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$_ips___x_retval .= "
							" . (($forum_data['redirect_on']) ? ("
								<li>
									<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", 'public','' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$forum_data['name']}</a> <span class='desc'>(Redirect)</span></h4>
								</li>
							") : ("<li>
									<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", 'public','' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$forum_data['name']}</a> <span class='desc'>( {$forum_data['topics']} {$this->lang->words['topics']} / {$forum_data['posts']} {$this->lang->words['replies']} )</span></h4>
									" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums']) ? ("
										<h4 class='hide'>{$this->lang->words['subforums']}</h4>
										<ol class='subforums'>
										".$this->__f__2134e8580b542710da3e81047cc9d4f7($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."										</ol>
									") : ("")) . "
								</li>")) . "
						
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__a36796a478eb074de2f1aba2739e8f1e($lastvisit="", $stats=array(), $calendar_events=FALSE, $birthdays=FALSE, $chat_html='', $news_data=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	foreach( $cat_data as $_data )
	{
		
		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
					<h3 id='category_{$_data['cat_data']['id']}' class='maintitle'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", 'public','' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='{$this->lang->words['view_cat']}'>{$_data['cat_data']['name']}</a></h3>
					
					<ol class='lofi_list'>
						".$this->__f__d01f2b4019ec1ea149cdd8437e8d4c28($lastvisit,$stats,$calendar_events,$birthdays,$chat_html,$news_data,$cat_data,$show_side_blocks,$side_blocks,$_data)."					</ol>
				") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($rows) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- hookRecentBlogEntries --*/
function hookRecentBlogEntries($entries) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- hookRecentGalleryImages --*/
function hookRecentGalleryImages($rows) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- hookTopPosters --*/
function hookTopPosters($posters) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- hookWatchedItems --*/
function hookWatchedItems($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- whoschatting_empty --*/
function whoschatting_empty() {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- whoschatting_show --*/
function whoschatting_show($total="",$names="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>