<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:25 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_printpage_3 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- choose_form --*/
function choose_form($fid="",$tid="",$title="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- pp_end --*/
function pp_end() {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- pp_header --*/
function pp_header($forum_name="",$topic_title="",$topic_starter="",$fid="",$tid="",$css=array(),$IPS_DOC_CHAR_SET=IPS_DOC_CHAR_SET) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- pp_postentry --*/
function pp_postentry($poster="",$entry="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>