<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 04:32:25 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_calendar_3 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- cal_approve_button --*/
function cal_approve_button($id="",$cal_id="",$event="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_blank_cell --*/
function cal_blank_cell() {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_date_cell --*/
function cal_date_cell($month_day="",$events="",$cal_date_queued="",$queued=0, $js_id) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_date_cell_today --*/
function cal_date_cell_today($month_day="",$events="",$cal_date_queued="",$queued=0, $js_id) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_day_bit --*/
function cal_day_bit($day="", $id='') {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_edit_del_button --*/
function cal_edit_del_button($id="",$cal_id="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_events_end --*/
function cal_events_end() {
$IPBHTML = "";
$IPBHTML .= "</ul>";
return $IPBHTML;
}

/* -- cal_events_start --*/
function cal_events_start() {
$IPBHTML = "";
$IPBHTML .= "<ul>";
return $IPBHTML;
}

/* -- cal_events_wrap --*/
function cal_events_wrap($event="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_events_wrap_manual --*/
function cal_events_wrap_manual($url="",$text="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_events_wrap_range --*/
function cal_events_wrap_range($event="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_events_wrap_recurring --*/
function cal_events_wrap_recurring($event="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_new_row --*/
function cal_new_row($week="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_show_event --*/
function cal_show_event($event="",$member="",$event_type="",$edit_button="",$approve_button="",$type="",$date_ends="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_unapprove_button --*/
function cal_unapprove_button($id="",$cal_id="",$event="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_week_content --*/
function cal_week_content($calendars, $date="",$month="",$year="",$prev="",$next="", $cal_id=1) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_week_dayentry --*/
function cal_week_dayentry($wday="",$date="",$month="",$mid="",$year="",$events="",$queued=0) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_week_events_wrap --*/
function cal_week_events_wrap($link="",$text="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- cal_week_events_wrap_range --*/
function cal_week_events_wrap_range($link="",$text="",$ft="",$bg="") {
$IPBHTML = "";
$IPBHTML .= "<div style=\"background-color: $bg; color: $ft; padding: 3px; border: 1px outset $bg; width: 50%;\">
	<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=calendar&amp;module=calendar&amp;$link", 'public','' ), "", "" ) . "' style=\"color: $ft;\">$text</a>
</div>";
return $IPBHTML;
}

/* -- cal_week_monthbar --*/
function cal_week_monthbar($month="",$year="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendar_rss_range --*/
function calendar_rss_range($event) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendar_rss_recurring --*/
function calendar_rss_recurring($event) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendar_rss_single --*/
function calendar_rss_single($event) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendarBirthdayList --*/
function calendarBirthdayList($rows) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendarEventForm --*/
function calendarEventForm($code="", $calendar_id="", $formtype="", $event_id='', $event_title='', $form_title='', $event_date='', $event_type='', $groups, $button, $editor) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendarEventsList --*/
function calendarEventsList($events) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- calendarMainContent --*/
function calendarMainContent($calendars, $month="",$year="",$prev="",$next="",$cal_jump="",$cal_id="",$day_words="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- mini_cal_blank_cell --*/
function mini_cal_blank_cell() {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- mini_cal_date_cell --*/
function mini_cal_date_cell($month_day="",$events="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- mini_cal_date_cell_today --*/
function mini_cal_date_cell_today($month_day="",$events="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- mini_cal_mini_wrap --*/
function mini_cal_mini_wrap($month="",$mid="",$year="",$events="",$day_words="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- mini_cal_new_row --*/
function mini_cal_new_row($week="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>