<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 01:36:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_help_2 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- helpShowSection --*/
function helpShowSection($one_text="",$two_text="",$three_text="", $text) {
$IPBHTML = "";
$IPBHTML .= "" . ((!$this->request['xml']) ? ("
<div class='topic_controls'>
	<ul class='topic_buttons'>
		<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['help_back_list_title']}\"><img src='{$this->settings['img_url']}/back.png' alt='Icon' /> {$this->lang->words['help_return_list']}</a></li>
	</ul>
</div>
") : ("")) . "
" . (($this->request['xml']) ? ("
<br />
") : ("")) . "
<h2>$one_text: $three_text</h2>
<div class='row2 help_doc bullets'>
	$text
</div>
<br />
" . ((!$this->request['xml']) ? ("
<div class='topic_controls'>
	<ul class='topic_buttons'>
		<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['help_return_list_title']}\"><img src='{$this->settings['img_url']}/back.png' alt='Icon' /> {$this->lang->words['help_return_list']}</a></li>
	</ul>
</div>
") : ("")) . "";
return $IPBHTML;
}

/* -- helpShowTopics --*/
function helpShowTopics($one_text="",$two_text="",$three_text="",$rows) {
$IPBHTML = "";

$this->registry->templateStriping['help'] = array( FALSE, "row1","row2");
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("help", "0" ) . "
<h2>{$this->lang->words['help_topics']}</h2>
<p class='message unspecific'>$two_text</p>
<ol id='help_topics'>
		".$this->__f__2ea0ed43840c1668a67680c1f8e33912($one_text,$two_text,$three_text,$rows)."</ol>";
return $IPBHTML;
}


function __f__2ea0ed43840c1668a67680c1f8e33912($one_text="",$two_text="",$three_text="",$rows)
{
	$_ips___x_retval = '';
	foreach( $rows as $entry )
	{
		
		$_ips___x_retval .= "
	<li class='" .  IPSLib::next( $this->registry->templateStriping["help"] ) . " helpRow'>
		<h3><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help&amp;do=01&amp;HID={$entry['id']}", 'public','' ), "", "" ) . "\" title=\"{$this->lang->words['help_read_document']}\">{$entry['title']}</a></h3>
		<p>
			{$entry['description']}
		</p>
	</li>
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>