<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 01:36:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_topic_2 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- announcement_show --*/
function announcement_show($announce="",$author="") {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("topic", "0" ) . "
<h2>{$this->lang->words['announce_title']}: {$announce['announce_title']}</h2>
<ul class='topic_options'></ul>
<div class='post_block first hentry announcement' id='announce_id_{$announce['announce_id']}'>
	<div class='post_wrap'>
		" . (($author['member_id']) ? ("
			<h3>
		") : ("
			<h3 class='guest'>
		")) . "" . (($author['member_id']) ? ("" . (($author['_online']) ? ("" . $this->registry->getClass('output')->getReplacement("user_online") . "") : ("" . $this->registry->getClass('output')->getReplacement("user_offline") . "")) . " &nbsp;
							<address class=\"author vcard\"><a class=\"url fn\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$author['member_id']}", 'public','' ), "", "" ) . "'>{$author['members_display_name']}</a>" . $this->registry->getClass('output')->getTemplate('global')->user_popup($author['member_id']) . "</address>") : ("
					{$author['members_display_name']}
				")) . "
			</h3>
		<div class='author_info'>
			" . $this->registry->getClass('output')->getTemplate('global')->userInfoPane($author, 'announcement', array()) . "
		</div>
		<div class='post_body'>
			<div class='post entry-content'>
				{$announce['announce_post']}
			</div>
		</div>
		<ul class='post_controls'></ul>
	</div>			
</div>";
return $IPBHTML;
}

/* -- build_threaded --*/
function build_threaded($post, $child) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- pollDisplay --*/
function pollDisplay($poll, $topicData, $forumData, $pollData, $showResults) {
$IPBHTML = "";
$IPBHTML .= "<poll>
	<title>{$poll['poll_question']}</title>
	" . (($showResults) ? ("<totalvotes>{$poll['_totalVotes']}</totalvotes>") : ("")) . "
	<public>{$this->settings['poll_allow_public']}</public>
	
	<questions>".$this->__f__a3ce54bc6a6e349c126f6514ab64cd2c($poll,$topicData,$forumData,$pollData,$showResults)."	</questions>
</poll>";
return $IPBHTML;
}


function __f__ad39005fe2b84776bf0645e4d4fb221b($poll, $topicData, $forumData, $pollData, $showResults,$questionID='',$questionData='',$choiceID='',$choiceData='')
{
	$_ips___x_retval = '';
	foreach( $choiceData['voters'] as $id => $member )
	{
		
		$_ips___x_retval .= "
					<user>
						<id>{$member['member_id']}</id>
						<name>{$member['members_colored_name']}</name>
						<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser=", 'public','' ), "{$member['members_seo_name']}", "showuser" ) . "</url>
					</user>						
					
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__ea638f3dffef320f418d4140c979a469($poll, $topicData, $forumData, $pollData, $showResults,$questionID='',$questionData='')
{
	$_ips___x_retval = '';
	foreach( $pollData[ $questionID ]['choices'] as $choiceID => $choiceData )
	{
		
		$_ips___x_retval .= "
				<choice>{$choiceData['choice']}</choice>
			" . (($showResults) ? ("<selected>" . ((is_array( $choiceData['voters'] ) AND in_array( $this->memberData['member_id'], array_keys( $choiceData['voters'] ) )) ? ("1") : ("0")) . "</selected>
				<votes>{$choiceData['votes']}</votes>
				<percent>{$choiceData['percent']}%</percent>
				
				" . (($poll['poll_view_voters'] AND is_array( $choiceData['voters'] ) AND $this->settings['poll_allow_public']) ? ("
				<voters>					
					".$this->__f__ad39005fe2b84776bf0645e4d4fb221b($poll,$topicData,$forumData,$pollData,$showResults,$questionID,$questionData,$choiceID,$choiceData)."				</voters>
				") : ("")) . "") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__a3ce54bc6a6e349c126f6514ab64cd2c($poll, $topicData, $forumData, $pollData, $showResults)
{
	$_ips___x_retval = '';
	foreach( $pollData as $questionID => $questionData )
	{
		
		$_ips___x_retval .= "			
		<question>
			<title>{$pollData[ $questionID ]['question']}</title>
	" . ((! $this->settings['allow_result_view'] AND ! $this->memberData['member_id']) ? ("
			<error>{$this->lang->words['poll_noview_guest']}</error>
	") : ("
			<results>
		".$this->__f__ea638f3dffef320f418d4140c979a469($poll,$topicData,$forumData,$pollData,$showResults,$questionID,$questionData)."			</results>
	")) . "
		</question>

";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

/* -- quickEditPost --*/
function quickEditPost($post) {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- show_attachment_title --*/
function show_attachment_title($title="",$data="",$type="") {
$IPBHTML = "";
$IPBHTML .= "";
return $IPBHTML;
}

/* -- Show_attachments --*/
function Show_attachments($data="") {
$IPBHTML = "";
$IPBHTML .= "<attachment>
	<id>{$data['attach_id']}</id>
	<thumbnail>" . (($data['attach_thumb_location']) ? ("{$this->settings['upload_url']}/{$data['attach_thumb_location']}") : ("")) . "</thumbnail>
	<name>{$data['short_name']}</name>
	<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=attach&amp;section=attach&amp;attach_rel_module=post&amp;attach_id={$data['attach_id']}", 'public','' ), "", "" ) . "</url>
	<downloads>{$data['attach_hits']}</downloads>
	<date>{$data['attach_date']}</date>
	<size>{$data['real_size']}</size>
	<post>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=findpost&amp;pid={$data['pid']}", 'public','' ), "", "" ) . "</post>		
</attachment>";
return $IPBHTML;
}

/* -- Show_attachments_img --*/
function Show_attachments_img($file_name="") {
$IPBHTML = "";
$IPBHTML .= "<attachment>
	<url>{$this->settings['upload_url']}/$file_name</url>
</attachment>";
return $IPBHTML;
}

/* -- Show_attachments_img_thumb --*/
function Show_attachments_img_thumb($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<attachment>
	<id>{$data['attach_id']}</id>
	<thumbnail>" . (($data['attach_thumb_location']) ? ("{$this->settings['upload_url']}/{$data['attach_thumb_location']}") : ("")) . "</thumbnail>
	<name>{$data['short_name']}</name>
	<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=attach&amp;section=attach&amp;attach_rel_module=post&amp;attach_id={$data['attach_id']}", 'public','' ), "", "" ) . "</url>
	<downloads>{$data['attach_hits']}</downloads>
	<date>{$data['attach_date']}</date>
	<size>{$data['real_size']}</size>
	<post>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=findpost&amp;pid={$data['pid']}", 'public','' ), "", "" ) . "</post>		
</attachment>";
return $IPBHTML;
}

/* -- topicViewTemplate --*/
function topicViewTemplate($forum, $topic, $post_data, $displayData) {
$IPBHTML = "";
$IPBHTML .= "<forum>
		<name>{$forum['name']}</name>
		<id>{$forum['id']}</id>
		<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum['id']}", 'public','' ), "{{$forum['name_seo']}", "showforum" ) . "</url>
		
" . (($forum['show_rules'] == 2) ? ("
		<rules>
			<title>{$forum['rules_title']}</title>
			<text>{$forum['rules_text']}</text>
		</rules>
") : ("")) . "
" . (($forum_data['show_rules'] == 1) ? ("
		<rules>
			<title>{$forum['rules_title']}</title>
			<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum['id']}&amp;act=SR", 'public','' ), "", "" ) . "</url>
		</rules>
") : ("")) . "
	
		<topic>
			<id>{$topic['tid']}</id>
			<title>{$topic['title']}</title>
			<description>{$topic['description']}</description>
			<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}", 'public','' ), "{$topic['title_seo']}", "showtopic" ) . "</url>
			
			{$displayData['poll_data']}
			
			<posts>				
" . ((is_array( $post_data ) AND count( $post_data )) ? ("".$this->__f__8259ed9d1be523210f389153c31eed29($forum,$topic,$post_data,$displayData)."") : ("")) . "
			</posts>
			{$topic['SHOW_PAGES']}
		</topic>
	</forum>
	
" . ((is_array( $displayData['active_users'] ) AND count( $displayData['active_users'] )) ? ("<activeusers>
			<total>" . intval( $displayData['active_users']['members'] + $displayData['active_users']['guests'] + $displayData['active_users']['anon'] ) . "</total>
			<guests>{$displayData['active_users']['guests']}</guests>
			<anonymous>{$displayData['active_users']['anon']}</anonymous>			
	" . ((is_array( $displayData['active_users']['names'] ) AND count( $displayData['active_users']['names'] )) ? ("
			<users>
		".$this->__f__ae2767558d2efbe57eff4684711432f4($forum,$topic,$post_data,$displayData)."			</users>
	") : ("")) . "
		</activeusers>") : ("")) . "";
return $IPBHTML;
}


function __f__8259ed9d1be523210f389153c31eed29($forum, $topic, $post_data, $displayData)
{
	$_ips___x_retval = '';
	foreach( $post_data as $pid => $post )
	{
		
		$_ips___x_retval .= "
				<post>
					<id>{$post['post']['pid']}</id>
					<date>" . $this->registry->getClass('class_localization')->getDate($post['post']['post_date'],"long", 0) . "</date>
					<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['post']['topic_id']}&amp;view=findpost&amp;p={$post['post']['pid']}", 'public','' ), "{$topic['title_seo']}", "showtopic" ) . "</url>
					<text>{$post['post']['post']}{$post['post']['attachmentHtml']}</text>
					<reputation>{$post['post']['rep_points']}</reputation>
		" . (($post['post']['icon_id']) ? ("
					<icon>{$this->settings['public_dir']}style_extra/post_icons/icon{$post['post']['icon_id']}.gif</icon>
		") : ("")) . "					
					<user>
		" . (($post['author']['member_id']) ? ("
						<id>{$post['author']['member_id']}</id>
						<name>{$post['author']['members_display_name']}</name>
						<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$post['author']['member_id']}", 'public','' ), "{$post['author']['members_seo_name']}", "showuser" ) . "</url>
						<online>{$post['author']['_online']}</online>
						" . $this->registry->getClass('output')->getTemplate('global')->userInfoPane($post['author'], $post['post']['pid'], array()) . "
		") : ("
						<id>0</id>
						<name>{$post['author']['members_display_name']}</name>
		")) . "
					</user>
		" . (($post['post']['edit_by']) ? ("
					<edited>
						<reason>{$post['post']['post_edit_reason']}</reason>
						<by>{$post['post']['edit_by']}</by>
					</edited>
		") : ("")) . "
					<signature>
						<![CDATA[
						{$post['post']['signature']}
						]]>						
					</signature>
				</post>				
	
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}

function __f__ae2767558d2efbe57eff4684711432f4($forum, $topic, $post_data, $displayData)
{
	$_ips___x_retval = '';
	foreach( $displayData['active_users']['names'] as $p => $r )
	{
		
		$_ips___x_retval .= "
				<user>
					<id>{$r['id']}</id>
					<name>{$r['p_start']}{$r['name']}{$r['p_end']}</name>
					<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['id']}", 'public','' ), "{$r['seo']}", "showuser" ) . "</url>
				</user>
		
";
	}
	$_ips___x_retval .= '';
	return $_ips___x_retval;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>