<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Sun, 06 Sep 2009 01:36:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ccs_2 {

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	/* Make object */
	$this->registry   =  $registry;
	$this->DB         =  $this->registry->DB();
	$this->settings   =& $this->registry->fetchSettings();
	$this->request    =& $this->registry->fetchRequest();
	$this->lang       =  $this->registry->getClass('class_localization');
	$this->member     =  $this->registry->member();
	$this->memberData =& $this->registry->member()->fetchMemberData();
	$this->cache      =  $this->registry->cache();
	$this->caches     =& $this->registry->cache()->fetchCaches();
}
	/* -- pageSearchResult --*/
function pageSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<span class='gutter'><img src='{$this->settings['public_dir']}style_extra/app_icons/ccs.png' alt='icon' /> {$this->lang->words['ccs_search_button']}</span>
<div>
	<div class='date' style='float:right;'>
		{$this->lang->words['page_last_updated']}  " . $this->registry->getClass('class_localization')->getDate($r['updated'],"short", 0) . "
	</div>		
</div>
<h3><a href='{$r['formatted_url']}'>{$r['content_title']}</a></h3>
" . ((!$resultAsTitle) ? ("
<p>
	{$r['content']}
</p>
") : ("")) . "";
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>